### ISSUE TITLE
Remove Arachnid and Mite?

### ISSUE THREAD

**Issue by Amazinite** [Amazinite/Shields-Up#1]
Tufton's Arachnid and Mite ships (used by the Hai) have been remade, redesigned, and added into the game by Wrzl and Local as the Solifuge and Violin Spider. Should we remove them from Tufton's plugin for the sake of compatibility then?

**Comment by Disiuze** [comment]
Just remove it from fleets and sales; people who have them don't lose them and the willing can readd them themselves.

**Comment by Amazinite** [comment]
That was my thought.

**Comment by FriendlyNeighbour** [comment]
I agree with that. I haven't sat down and played Endless Sky for a bit, I wasn't even aware that they were officially added xD

**Comment by Amazinite** [comment]
7d7ca41
