### ISSUE TITLE
Move Tuk'ux Systems?

### ISSUE THREAD

**Issue by Amazinite** [Amazinite/Shields-Up#10]
They take up so much space for how few systems there are.
http://prntscr.com/c7cqtb
Plus, it takes 5 jumps to get from that one system to the one right next to it, because it's like one pixel outside of jump range...

**Comment by FriendlyNeighbour** [comment]
I would recommend talking with Pompano on that one, since they are his systems. Although I agree that they should be moved a bit closer together (for the reason that you stated).

**Comment by Amazinite** [comment]
Does he even care anymore?

**Comment by FriendlyNeighbour** [comment]
I just recently talked with him about his mod, so I'd assume so.

**Comment by Amazinite** [comment]
I'll ask him about it.

**Comment by FriendlyNeighbour** [comment]
btw, aside from most sites being blocked by admin privileges on these laptops, github isn't blocked. woot. I won't be able to run github desktop though.

**Comment by Amazinite** [comment]
He said he'd update it late tonight.

**Comment by FriendlyNeighbour** [comment]
alrighty

**Comment by Amazinite** [comment]
He didn't do it.

**Comment by Disiuze** [comment]
Add a file to SU which moves them.

**Comment by Amazinite** [comment]
Pompano says he has moved them on his end, but won't let me update his main to the repo until he finishes a new alien race... That was like last week.

**Comment by Disiuze** [comment]
> Add a file to SU which moves them

**Comment by Amazinite** [comment]
b801e50
Note the commit description

**Comment by Disiuze** [comment]
o

**Comment by Amazinite** [comment]
826e8ad moved them.
