### ISSUE TITLE
An issue on ships and where they are sold

### ISSUE THREAD

**Issue by Amazinite** [Amazinite/Shields-Up#105]
Pretty much the same thing as #104, but with ships instead.

**Comment by Amazinite** [comment]
Transport:
- Skybus (SU), a Firebird mod
- Archangel (SU), an upgrade to the Star Queen
- Star Princess (PF), a smaller Star Queen
- Silver Stream (PF)
- Rum Barrel (PF), Shameless Privateer

Super Transport:
- Gnosis Transport (SU), a Syndicate Bulk Freighter fitted for transporting

Light Freighter:
- Vagabond (SU), an old Clipper with parts replaced
- Lifted Purse (PF), Shameless Privateer
- Pilfered Keg (PF), Shameless Privateer
- Buried Chest (PF), Shameless Privateer
- Captain's Hoard (PF), Shameless Privateer
- 3000X2 Freight (PF)
- 3500X2 Freight (PF)

Heavy Freighter:
- Ancient Hulk (SU), an old Bulk Freighter, currently unused
- Modified Firebird (SU), pirate freighter
- Gargoyle (PF), a lighter Behemoth
- Hauler IV (PF)
- 4500X2 Freight (PF)
- 4500X2A Freight (PF)

Super Freighter:
- Hauler VI (PF)
- Hauler XV (SU)
- 7000X2S Freight (PF)
- 8500X2S Freight (PF)
- 10000X2S Freight (PF)

Interceptor:
- FTek Hornet (SU), a modified Sparrow
- FTek Girl Scout (SU), a cool lookin interceptor
- Dark Berserker (PF), a modified Berserker
- Black Hawk (PF), a modified Hawk
- Elepaio (PF), a Tarazed upgrade to the Sparrow
- Sparrow MKII (PF), what it sounds like
- Wren (PF), a high speed single turret interceptor
- Fifth Ace (PF), Shameless Privateer
- Hidden Blade (PF), Shameless Privateer
- Dirty Cutlass (PF), Shameless Privateer

Light Warship:
- Vagrant (SU), a bootleg Rainmaker
- Therum (SU), a Headhunter w/ 3 guns and no turrets, designed to carry heavy weapons
- Arrowhead (PF), a multi-purpose Syndicate warship
- Light Dart (PF), a noticably fast human warship
- Heavy Dart (PF), a slightly better Light Dart, only slightly better in combat but far better in cargo
- Swooping Raven (PF), a more combat focused Raven
- Junior Osprey (PF), a light warship Osprey
- Gunboat GXV2 (PF), a modified Gunboat
- Camelthorn (PF), New Bounty
- Balau (PF), New Bounty
- Silver Escort (PF)
- Fearless Assassin (PF), Shameless Privateer
- Deceitful Hangman (PF), Shameless Privateer

Medium Warship:
- Legionnaire (SU), a combat-focused Mule
- Pirated Frigate (SU), a stolen and modified Navy Frigate
- FTek Destroyer (SU), a modified Freighter
- Aerie (Drone) (SU), what it sounds like
- Destroyer (PF), a Navy ship between the Cruiser and Frigate
- Cebil (PF), New Bounty
- Quebracho (PF), New Bounty
- Gidgee (PF), New Bounty
- Black Star (PF), part of the Silver series of ships
- Silver Protector (PF)
- Stormbolt (PF), Shameless Privateer
- Deceptive Lover (PF), Shameless Privateer
- Hellscream (PF), Shameless Privateer
- Damned Executioner (PF), Shameless Privateer
- 4500X2 Gunship (PF)

Heavy Warship:
- Derelict (SU), a modified Leviathan
- Ironclad Battleship and Carrier (SU), ancient heavy ships, almost entirely hull
- Inferno (SU), a heavy Firebird
- Trailbreaker (PF), a capital Vanguard
- Fortress (PF), a capital Protector
- Wamara (PF), New Bounty
- Silver Star (PF), a stronger Black Star
- X2 Gunship (PF)
- X2E Gunship (PF)

Capital Ship: 
- Phoenix (SU), another heavy Firebird
- Samurai (SU), a Syndicate capital ship
- Kestrel-M (SU), a premium Kestrel hull, unlocked along side Kestrel
- Bactrian T2 (SU), a premium Bactrian hull, unlocked after main plot
- Dragoon (SU), a new Lionheart ship
- Lignum (PF), New Bounty
- Katalox (PF), New Bounty
- Silver Defender (PF)

Supercapital:
- Monolith (SUL), currently unused
- Kriegsmacher (SU), a megaship unlocked by getting max combat rating
- Capitalis Viatoris (SU), a supercapital made by Tarazed, not currently used
- Alliance Battleship (PF), a collaboration between Lionheart and Navy shipyards to make an upscaled Bactrian

Fighter:
- Tactical Assault Fighter (SUL)
- Sky Dinghy (SU), a fighter transport

Drone:
- Hunter Drone (SU), comparable as the drone version of the Finch (in its customizability)

86 total

**Comment by Amazinite** [comment]
Scrapping the following:
- Gnosis Transport: super transports are dangerous to balance, so it might as well be thrown out
- Vagabond: no one wants an old ship
- Ancient Hulk: unused anyways
- FTek Hornet: no one wants a copy
- Aerie (Drone): see above
- Derelict: see above
- Sparrow MKII: see above
- Gargoyle: see above
- Phoenix: we don't need two heavy versions of the Firebird
- Ironclad Battleship: we don't need two Ironclads
- The silver series of ships: they have no colored markings, and therefore have little place in the game. Phil also said in #75 that they were pretty much just thrown in last second
  - Silver Defender
  - Silver Star
  - Black Star
  - Silver Protector
  - Silver Escort
  - Silver Stream
- X2E Gunship: we don't need two X2 Gunships
- Buried Chest: too similar in appearance to the Captain's Hoard while being far worse in its stats
- Gunboat GXV2: too similar in appearance to the normal Gunboat and no real reason for existing.
- Removing some X2 heavy freighters and a Hauler, because there doesn't need to be 5 X2 heavy freighters and 5 heavy Haulers.
  - 4500X2A Freight
  - 8500X2S Freight
  - Hauler VI
- Elepaio: Redundant with the Hawk
- Deceptive Lover: Too many similar looking Shameless Privateer medium warships
- Damned Executioner: see above

Scrapping 25

**Comment by Amazinite** [comment]
Story-gate:
- Tactical Assault Fighter: way too customizable for its class
  - A fighter developed by the Deep after seeing the effectivness of the Tarazed Finch
- Alliance Battleship: super capital, nuff said
  - A ship built by Lionheart and Navy shipyards for the purpose of fighting back against increased pirate activity.
- Capitalis Viatoris: see above
  - A Tarazed supercapital inspired by the Alliance Battleship. Needs a rename.
- Hunter Drone: see above
  - A drone developed by Tarazed to go alongside their new supercapital
- Kriegsmacher: see above
  - A megaship developed by a shadowy group of individuals that contact the combat-focused players.
- Monolith: see above
  - Make a Megaparsec supercapital. Probably comes about in the same way as the Tarazed supercapital
- Trailbreaker: the Syndicate don't make capitals in vanilla
  - Start getting used by the Syndicate during the war when they switch over to mark 2 tech. Released for sale after the war.
- Fortress: see above
- Destroyer: see above
  - Released after the war as a ship that was in development during the war but took too long to finish.
- Ironclad Carrier: an ancient ship that wouldn't normally be in production
  - A recreation by some guy in Southbound obsessed with old human tech
- Pirated Frigate: Where the heck are pirates getting Frigates from?
  -  Might pair w/ Mag Rail Cannon story as something the Pirates begin being able to make once they can quickly take down Navy ships
- Hauler XV: Too big for current Southbound hangars to create
  - With X2 making fancy new superfreighters that are driving competitors out, especially the old Haulers of the south, Southbound Shipyards needs to create their own freighter to be able to stay in the game.

Already story-gated:
- Dragoon: post-war capital 
- Bactrian T2: premium hull
- Kestrel-M: premium hull
- Samurai: post-war capital
- Legionnaire: mid-war combat medium

Gating 12
5 Gated

**Comment by Amazinite** [comment]
Remaining ships that aren't story-gated or scrapped

Transport:
- Skybus (SU), a Firebird mod
- Archangel (SU), an upgrade to the Star Queen
- Star Princess (PF), a smaller Star Queen
- Rum Barrel (PF), Shameless Privateer

Light Freighter:
- Lifted Purse (PF), Shameless Privateer
- Pilfered Keg (PF), Shameless Privateer
- Captain's Hoard (PF), Shameless Privateer
- 3000X2 Freight (PF)
- 3500X2 Freight (PF)

Heavy Freighter:
- Modified Firebird (SU), pirate freighter
- Hauler IV (PF)
- 4500X2 Freight (PF)

Super Freighter:
- 7000X2S Freight (PF)
- 10000X2S Freight (PF)

Interceptor:
- FTek Girl Scout (SU), a cool lookin interceptor
- Dark Berserker (PF), a modified Berserker
- Black Hawk (PF), a modified Hawk
- Wren (PF), a high speed single turret interceptor
- Fifth Ace (PF), Shameless Privateer
- Hidden Blade (PF), Shameless Privateer
- Dirty Cutlass (PF), Shameless Privateer

Light Warship:
- Vagrant (SU), a bootleg Rainmaker
- Therum (SU), a Headhunter w/ 3 guns and no turrets, designed to carry heavy weapons
- Arrowhead (PF), a multi-purpose Syndicate warship
- Light Dart (PF), a noticably fast human warship
- Heavy Dart (PF), a slightly better Light Dart, only slightly better in combat but far better in cargo
- Swooping Raven (PF), a more combat focused Raven
- Junior Osprey (PF), a light warship Osprey
- Camelthorn (PF), New Bounty
- Balau (PF), New Bounty
- Fearless Assassin (PF), Shameless Privateer
- Deceitful Hangman (PF), Shameless Privateer

Medium Warship:
- FTek Destroyer (SU), a modified Freighter
- Cebil (PF), New Bounty
- Quebracho (PF), New Bounty
- Gidgee (PF), New Bounty
- Stormbolt (PF), Shameless Privateer
- Hellscream (PF), Shameless Privateer
- 4500X2 Gunship (PF)

Heavy Warship:
- Wamara (PF), New Bounty
- X2 Gunship (PF)

Capital Ship:
- Lignum (PF), New Bounty
- Katalox (PF), New Bounty

Fighter:
- Sky Dinghy (SU), a fighter transport

44 remaining

**Comment by Elyssaen** [comment]
Generally strongly agree with your decisions here.

Let's see, though... the Junior Osprey doesn't look all that great and I've never understood it. I'd consider it for dropping.

The Silver ships, did PF originally say he expected them to be story-gated? I had an out-of-date version, but in it they were sold by Tarazed as a placeholder. Not sure if that changed.

**Comment by Amazinite** [comment]
I might actually rename the Junior Osprey and keep it, but I am considering dropping the silver ships since they have no markings and therefore are either only allowed to be from one faction or just can't be used at all. Phil talked about the silver ships here: #75

**Comment by Elyssaen** [comment]
Silver ships could maybe be put on the back shelf until some content makes use of them. Seems you'll be busy for a good long while on all the rest of the content.

**Comment by Amazinite** [comment]
Yeah, putting stuff on the shelf is what the housekeeping folder is for. Most of the stuff in that folder will probably never come back though.

**Comment by SentientCookie** [comment]
I didn't realize that the housekeeping folder was for back-shelved and removed material. I really like the idea that, even though some things are removed, they can still be accessed from the Forge.

Personally, I like the silver series ships, even though they lack colored markings. If the ships were to remain (unless they get potential colored markings), I would suggest that the pirate faction use them.

Also, I do agree with @Elyssaen about the Junior Osprey for the most part; I do, however, like that it feels like a pre-step to getting the Osprey. I also agree with @Amazinite that renaming it might be better than outright removing it; "Junior Osprey," as a name, kind-of feels like the kids meal version of the Osprey ship.

**Comment by Elyssaen** [comment]
A new name'd help, but I also think the Osprey is just one of the less impressive human ship sprites. It's a shame to try to make a variant of that, and I think it came out less well than Phil's capable of because the Osprey itself could do with a rework.

Also, Tarazed kind of have a light warship already in the Blackbird (yes, really). I wish I'd begged Phil to make a Blackbird Mk II instead of a Junior Osprey. : )

**Comment by SentientCookie** [comment]
I wish I knew how to make ship designs; I'd be (somewhat) unstoppable. I once attempted to make one in Blender for another project, but I failed at it horribly. ^_^;;

**Comment by Amazinite** [comment]
Thoughts on the Arrowhead? It's suppose to be Syndicate tech but it doesn't really fit in to me. Probably scrapping it.

Probably scrapping the Elepiao: it's made by Tarazed and suppose to be an upgrade to the Sparrow, which is already what the Hawk is (also made by Tarazed). Tempted to keep it though since I like the sprite.

Might scrap the Stormbolt and the Hellscream for the following reasons: 1) after their name changes, they're the only Shameless Privateer ships whos name is not two words. 2) SP doesn't need 4 medium warships, and the Stormbolt and Hellscream already look similar to the Deceptive Lover and Damed Executioner respectively.

**Comment by Amazinite** [comment]
Other than those four, I think everything that's in the keep list now is going to stay.

**Comment by Elyssaen** [comment]
I have opposite opinions to you here. : ) Quite like the Arrowhead, as it's a cute little turret boat. It's not as iconically pretty as the Dart Class ships but I like the mechanical niche, including in the Syndicate line-up as they have a lot of gunships.

Never really noticed the Elepaio one way or the other.

But the old Lightning in the Storm and Screams of the Insane were the Privateer ships I noticed and liked most. More than the 'Lover and 'Executioner, certainly. But that might just be me, and you're right that Shameless Privateer have a lot of ships.

**Comment by Amazinite** [comment]
Alright, I think the list is final now. Scrapping 25, story gating 11, and keeping 45 that can be found right when you start the game.

**Comment by Amazinite** [comment]
Deprecated those 25 ships in 115cf03. Now to figure out where exactly the current 45 ships should be sold.

**Comment by Amazinite** [comment]
The following are the ships not made by new shipyard manufacturers.

Transport:
- Skybus (SU): Betelgeuse
- Archangel (SU): Betelgeuse and Lionheart Advanced
- Star Princess (PF): Luxury + Syndicate Advanced

Heavy Freighter:
- Modified Firebird (SU): Northern Pirates
- Hauler IV (PF): Southbound

Interceptor:
- Dark Berserker (PF): Northern Pirates
- Black Hawk (PF): Southern Pirates
- Wren (PF): Tarazed

Light Warship:
- Vagrant (SU): Southbound
- Therum (SU): Southbound
- Arrowhead (PF): Megaparsec
- Light Dart (PF): Syndicate
- Heavy Dart (PF): Syndicate
- Swooping Raven (PF): Lionheart
- Junior Osprey (PF): Tarazed

Fighter:
- Sky Dinghy (SU): Betelgeuse

**Comment by Amazinite** [comment]
Ships made by new shipyards

Shameless Privateer will be based out of the Core
X2 will be based out of the Paradise Worlds
New Bounty will be based out of the South
FTek is just going to borrow Syndicate 'yards

Transport:
- Rum Barrel (PF): Privateer Basic

Light Freighter:
- Lifted Purse (PF): Privateer Basic
- Pilfered Keg (PF): Privateer Basic
- Captain's Hoard (PF): Privateer Basic
- 3000X2 Freight (PF): X2 Basic
- 3500X2 Freight (PF): X2 Basic

Heavy Freighter:
- 4500X2 Freight (PF): X2 Advanced

Super Freighter:
- 7000X2S Freight (PF): X2 Advanced
- 10000X2S Freight (PF): X2 Special

Interceptor:
- FTek Girl Scout (SU): Syndicate Basic
- Fifth Ace (PF): Privateer Basic
- Hidden Blade (PF): Privateer Basic
- Dirty Cutlass (PF): Privateer Basic

Light Warship:
- Camelthorn (PF): New Bounty Basic
- Balau (PF): New Bounty Basic
- Fearless Assassin (PF): Privateer Basic
- Deceitful Hangman (PF): Privateer Basic

Medium Warship:
- FTek Destroyer (SU): Syndicate Advanced
- Cebil (PF): New Bounty Advanced
- Quebracho (PF): New Bounty Advanced
- Gidgee (PF): New Bounty Advanced
- Stormbolt (PF): Shameless Privateer
- Hellscream (PF): Shameless Privateer
- 4500X2 Gunship (PF): X2 Advanced

Heavy Warship:
- Wamara (PF): New Bounty Advanced
- Lignum (PF): New Bounty Advanced
- X2 Gunship (PF): X2 Special

Capital Ship:
- Katalox (PF): New Bounty Special

**Comment by Amazinite** [comment]
And I just realized that the Hauler XV is too big for Southbound Shipyards to make, so it's going to need to be story-gated (the Dreadnaught was just barely able to fit in Southbound hangars).

**Comment by Amazinite** [comment]
bb219a2

X2 Shipyards was created by the daughter of a once great trader. After her father's death, she used her inheritance to continue her father's legacy of hauling fish across the stars, but this time in bigger and better ships of her own design. After moving from world to world in the Paradise region, looking for a planet to start her new business, she finally settled on the spa world of Calda and placed the first factory right next to a hot spring in a more remote region of the world.
Design philosophy: the more cargo, the better.

New Bounty is the Lionheart of the South, creating powerful and niche ships for those with enough money to pay (which doesn't happen often in the galactic backwaters of the South). Although, given that the South is not as technologically advanced as the Deep, their ships each lack in a certain way that some pilots like to avoid, so none of them are as perfect as many Lionheart ships are considered to be. In an agreement with Delta V, New Bounty has been allowed to create their main ship factories on Solace, but only if all New Bounty ships are sold with Delta V engines and weapons.
Design philosophy: changes from ship to ship, but generally try and hit different niches with each ship (high speed, high cargo, fleet anchors, etc).

Shameless Privateer in its new iteration retains the "barnacle in the side of the Syndicate" feeling, producing ships on all pirate planets around the Core. They are based in Buccaneer Bay, and produce cheap and easily produced ships, many of which designed to withstand a good beating to protect the booty inside of their larger-than-average cargo holds while they zip away with their high speeds.
Design philosophy: lots of cargo and lots of speed.

**Comment by Amazinite** [comment]
Now on to either writing descriptions for all the ships and outfits that have been kept or doing a balancing run on Phil's ships and outfits...

Edit: balancing run first, so I know what to write for the descriptions.
