### ISSUE TITLE
Remove these uninhabited systems?

### ISSUE THREAD

**Issue by Amazinite** [Amazinite/Shields-Up#11]
http://prntscr.com/c7cvi6

The Deep has been explain as being pretty much a galactic fortress that has only one way in and one way out, so for the sake of lore I think it would make sense to remove these uninhabited systems so that the Deep remains having only one entrance and exit.

Agon could probably stay, but the others should go.

**Comment by Amazinite** [comment]
Agon could probably stay, but the others should go.

**Comment by FriendlyNeighbour** [comment]
If memory serves, Beltane also has a wormhole in it. Agon and Beltane should stay, Maybe make them both require a jump-drive to reach. The reason those systems were there was for use in the story, however they could still be used for the same purpose. Keeping with the fortress aspect, we could make sure both systems are out of jump-drive range with Arneb and Alnilam.

**Comment by Amazinite** [comment]
41e8133
