### ISSUE TITLE
Internally conflicting systems

### ISSUE THREAD

**Issue by Amazinite** [Amazinite/Shields-Up#12]
These ones in location/links:
http://prntscr.com/c7d2q6

And these ones in their names hitting eachother at normal map zoom:
http://prntscr.com/c7d3aa
http://prntscr.com/c7d3q8
http://prntscr.com/c7d3wu

**Comment by FriendlyNeighbour** [comment]
As for http://prntscr.com/c7d3aa those systems need to be moved (the ones farther west) to remove the conflictions with the official claim an area of the map forum MZ started.
As for http://prntscr.com/c7d3q8 and http://prntscr.com/c7d3wu these can be moved as needed.

I have a question about http://prntscr.com/c7d2q6 Those shouldn't be in that position. (In fact, in my game that I just checked, they aren't. In fact 2x, they haven't been in that location for a couple updates, are you sure you have the latest update? Or perhaps you did something with that specific file?)

**Comment by Amazinite** [comment]
Yup, it was a load order situation.

**Comment by Amazinite** [comment]
Okay, the past four commits should have fixed everything but those systems around New New Providence. I'll leave that to you to work with, since I don't know what you want to do with them.
