### ISSUE TITLE
Screwed up ships

### ISSUE THREAD

**Issue by Amazinite** [Amazinite/Shields-Up#14]
Stats say 2 guns, 4 turrets. But the sprite shows 4 guns added onto a Freighter, which has 2 turrets.
![screenshot_2](https://cloud.githubusercontent.com/assets/17688683/17816698/8b338268-6608-11e6-9220-1d2a0626b9ee.png)
Pretty sure they're flipped.

**Comment by Amazinite** [comment]
On a related note, the Ironclad Battleship has 7 turret hardpoints in its sprite but only has 6 useable turrets. And the hardpoints are lobsided as well, so the Ironclad Battleship is going to need patching up.

**Comment by FriendlyNeighbour** [comment]
Yeah, thanks for pointing that out. I guess somewhere I messed up and flipped those points around.

**Comment by Amazinite** [comment]
Both Ironclads are messed up xD

**Comment by FriendlyNeighbour** [comment]
lol :P

**Comment by Amazinite** [comment]
Archangel's guns and engines aren't even on its sprite.

**Comment by Amazinite** [comment]
~~One~~ Two of the Tuk'ux Battle carrier guns are off from where they should be and the Tuk'ux fighters come stock with double the idle heat than their heat capacity is.
