### ISSUE TITLE
FTek Homing Blaster

### ISSUE THREAD

**Issue by Amazinite** [Amazinite/Shields-Up#16]
The useless submunitions cause so much lag.

**Comment by FriendlyNeighbour** [comment]
I agree, I also was going to heavily nerf them. Similarly, I was planning on locking some of the FTek outfits (at least, the more advanced outfits) behind a mission chain. This way they become a part of the world in a bit more gradual manner, as opposed to just being plopped right in the player's face almost wherever they go.

**Comment by Amazinite** [comment]
9eb0169
