### ISSUE TITLE
EMP Bomb

### ISSUE THREAD

**Issue by Amazinite** [Amazinite/Shields-Up#17]
Image is too big.
I'm pretty much just playing right now and writing down all the issues I'm finding here.

**Comment by FriendlyNeighbour** [comment]
I believe you may want to check the Mil'taj Black Generator (maybe the grey, I can't remember from the top of my head) I believe I need to fix the size on that as well.

**Comment by Amazinite** [comment]
Yeah, the Grey one is a little big too, but the Black one is fine.

**Comment by Disiuze** [comment]
EMP Bomb image now fixed.

**Comment by Amazinite** [comment]
Fixed the Grey Generator.
