### ISSUE TITLE
Stock Ship Outfits

### ISSUE THREAD

**Issue by Amazinite** [Amazinite/Shields-Up#19]
A lot of ships are running negative space in outfit, weapon, or engine capacity.
![screenshot_1](https://cloud.githubusercontent.com/assets/17688683/17824435/f580b10a-662f-11e6-8eff-5a8fe8562ff4.png)
Some of Pompano's ships don't even have any engine space or weapon space.
![screenshot_2](https://cloud.githubusercontent.com/assets/17688683/17824437/f64230c8-662f-11e6-9acb-ff93e2c85da1.png)

**Comment by Amazinite** [comment]
Wait; do Alpha ships have internal energy generation?

Edit: Nope, the generators are just listed under systems instead of power.

**Comment by FriendlyNeighbour** [comment]
In the early stages of the mod, that was one of the things I went over most xD
I suppose I missed some of the ships (or maybe made some changes to sizes and forgot to check the space, xD)
