### ISSUE TITLE
Some unused outfit images

### ISSUE THREAD

**Issue by Amazinite** [Amazinite/Shields-Up#21]
Remove?
![small core](https://cloud.githubusercontent.com/assets/17688683/17827772/ee660a52-6650-11e6-9f05-989190d28e4f.png)
![medium core](https://cloud.githubusercontent.com/assets/17688683/17827774/f02a7148-6650-11e6-952f-4adbe7d15824.png)
![droid](https://cloud.githubusercontent.com/assets/17688683/17827776/f236e142-6650-11e6-886e-6e259949b087.png)
![bug_1](https://cloud.githubusercontent.com/assets/17688683/17827777/f2c22022-6650-11e6-8030-50aee827af2d.png)
![bug](https://cloud.githubusercontent.com/assets/17688683/17827778/f378c64c-6650-11e6-88fe-ff14e6720172.png)
![fighterbay](https://cloud.githubusercontent.com/assets/17688683/17827780/ff9dc404-6650-11e6-882e-a74f98f5395f.png)

Pretty sure this one isn't used either
![ftek capaciter2](https://cloud.githubusercontent.com/assets/17688683/17827784/091e64d4-6651-11e6-9940-468681a0ec6f.png)

Plus, there's some images in here that are nothing more than copies of vanilla images with different names.

**Comment by Amazinite** [comment]
And what's with these _1 and full res images?

**Comment by FriendlyNeighbour** [comment]
All of those were either older outfit images or placeholders.
Although that battery is actually two batteries in one. xD

**Comment by Amazinite** [comment]
Oh yeah, This. bb701fc
