### ISSUE TITLE
FTek Hornet speed

### ISSUE THREAD

**Issue by FriendlyNeighbour** [Amazinite/Shields-Up#22]
As of now, the FTek Hornet is way too fast.

**Comment by Amazinite** [comment]
Oh really. Let me test this ou-HOLY CRAP!

But srsly, if it's suppose to be a copy (I mean it's totally not a copy. It's completely different, can't you tell?). you might as well just give it the exact same stats as the Sparrow but w/ FTek outfits instead.

Speaking of which, the Hornet says it comes with Active Blasters, but when you buy it there are no blasters on it at all.

**Comment by Amazinite** [comment]
For the sake of clearing issues, I've increase the Hornet's drag from 0.5 to 1.2 in b6b0fae, which is 0.2 greater than that of the Sparrow to compensate for the Hornet's 20 more engine space. I'll do a full rebalance later, as with the rest of the human ships.
