### ISSUE TITLE
Missing descriptions

### ISSUE THREAD

**Issue by FriendlyNeighbour** [Amazinite/Shields-Up#23]
Some items (such as Anti-Ship Battery) need descriptions.

**Comment by Amazinite** [comment]
Yeah, and a lot of the existing descriptions are kind of bland. I'll put a total SU balance/description overhaul on my todo list for after I finish Enigma Corp v0.5.5 and have nothing to do, pretty much giving it the same makeover I gave my mod in v0.5.4 and am giving in v0.5.5.

**Comment by Amazinite** [comment]
Aside from the ASB (which is part of Tak's mod anyways) what is missing a description?

**Comment by Amazinite** [comment]
Aside from the ASB (which is part of Tak's mod anyways) what is missing a description?

**Comment by Amazinite** [comment]
Outsourced to a card in the `Focus for next update` column of the [roadmap project](https://github.com/Amazinite/Shields-Up/projects/1).
