### ISSUE TITLE
Limit Sell Locations of FTek goodies?

### ISSUE THREAD

**Issue by FriendlyNeighbour** [Amazinite/Shields-Up#24]
It may be a good idea to slightly decrease the amount of systems that FTek's weapons and ships get sold in, concentrating them a bit more in the south-east.

**Comment by Amazinite** [comment]
Maybe some of it could be widely available, but keep the good stuff located in a more centralized area like the Core.

**Comment by FriendlyNeighbour** [comment]
That's kinda what I have now, the best stuff is the the south-east, and some stuff is spread to FW space.

**Comment by FriendlyNeighbour** [comment]
Should be resolved now.
