### ISSUE TITLE
Plenipotent Dominion using pirate names

### ISSUE THREAD

**Issue by FriendlyNeighbour** [Amazinite/Shields-Up#25]
For some reason, even though the PD has their own name list (which they do use) they for some reason use the vanilla pirate ship names. I have been aware of this issue for a while, but have yet to find out the cause.

**Comment by Amazinite** [comment]
e4d8a71 should fix. You had extra tabs next to the name lines.

**Comment by Amazinite** [comment]
I'm not seeing any Plenipotent fleets with pirate names, Is it good for you?
