### ISSUE TITLE
FTek Active vs Heavy Blaster

### ISSUE THREAD

**Issue by Amazinite** [Amazinite/Shields-Up#26]
Which is suppose to be better?
Because right now, the Active Blaster weighs less but is more powerful than the Heavy Blaster.

Just need to know for when I do the rebalancing.

**Comment by FriendlyNeighbour** [comment]
Well the active is supposed to fire faster, be less accurate, and use a smaller amount of energy (so less shots hit, more shots are fired, less damage per shot) and the heavy is supposed to be smaller numbers of shots, more accurate, and more damage. I never really got around to balancing them (not to mention the homing blaster...)

**Comment by Amazinite** [comment]
76c924f
