### ISSUE TITLE
Were you not removing the regional pirates?

### ISSUE THREAD

**Issue by Amazinite** [Amazinite/Shields-Up#3]
I thought the regional pirates were suppose to be removed as to keep compatibility with other mods, or at least only be used during missions that involve them. If so, I can go through and change the relevant information to remove them from fleets and such.

**Comment by Disiuze** [comment]
TBH, they should be removed.

**Comment by FriendlyNeighbour** [comment]
Yeah, they should be removed. Might require some reworking with the fleets, I don't believe the vanilla pirate fleets have a file in SU that adds our modded ships. (They possibly do, I'd have to check.)

**Comment by Amazinite** [comment]
Speaking of fleets, some merchant fleets have pirate ships, which seems odd to me. The one I've seen is the Pirated Frigate. And if the Pirated Frigate is in a pirate fleet, it should only be in the northern pirate fleets given their proximity to the Navy.

**Comment by FriendlyNeighbour** [comment]
Hm, that's strange (regarding the merchants). We'd have to fix that up, and if we're getting rid of the different pirate factions than the pirated frigate would still be distributed to all the pirates :/

Speaking of which, this reminded me of a couple system overlapping issues with some of the official mod systems added to the claim a piece of the map thing that MZ set up. I can get to fixing that. (it was the north-west and west systems that had the issue.)

**Comment by Amazinite** [comment]
> and if we're getting rid of the different pirate factions than the pirated frigate would still be distributed to all the pirates :/

No, because there are still regional pirate fleets in vanilla, just not regional pirate factions.

**Comment by Amazinite** [comment]
fae8d0f
Unless I missed something outside of the SU folder, there was only one regional pirate fleet left xD
Should I remove the governments as well?

**Comment by FriendlyNeighbour** [comment]
Might as well. xD

**Comment by Amazinite** [comment]
40889a5
