### ISSUE TITLE
Plenipotent and Servorum + Faction Tiering

### ISSUE THREAD

**Issue by Amazinite** [Amazinite/Shields-Up#30]
What is the difference between the two?

The Dominion seems more Tier 1 or 1.1, at least in their ships, but the Dei are far more T2 or T3 even.

Proposal: Have most of the Dominion ships be T1.1 / Hai level in power, and then the Kukri along with those unused ships could be T1.5-ish. Then Servorum would be T2. This allows for a ramp up in difficulty against the Alphas, and gives the player more stepping stones in terms of power. Then the Mil'taj might be T2.5, to bridge the gap between the Wanderers, Korath, and Servorum against the Quarg

**Comment by Amazinite** [comment]
ANSWER MEEEEEEEEE

**Comment by FriendlyNeighbour** [comment]
Well the Dominion and Servorum are supposed to be kinda flipped there. Dominion > Servorum. Stat-wise, I'm fairly certain Dominion are better, and number wise (frequency of fleet spawn, strength of fleets) the Dominion is better as well. I agree with the Mil'taj T2.5.

**Comment by Amazinite** [comment]
So... what about the rest then?
I really think we should do a T1.1, T1.5, and T2 system for that ramp up in power. 

And how about a story explanation as to why the Dominion is suppose to be greater than the Servorum? It would make balancing easier on me.

**Comment by Amazinite** [comment]
```
Dominion's main battle force: T1.1
    (Corvo, Napoo, Nefandous, Sica, Stiletto)
Servorum: T1.5
    (Albacore, Arowana, Catla, Cisco, Gourami)
Dominion's stronger ships: T2
    (Dirk, Gunong, Kukri, Pugio, Spetum?)
Mil'Taj: T2.5
    (Ballista, Bodkin, Curtana, Halberd, Pilum)
Dominion's Battlestar: T3
```

Cool, 5 ships in each category, excluding the Battlestar.

> But Muh Wage Gap: so the Dominion and Servorum both get help from the Mil'taj, hence why their weapons and shields are mil'taj
> But Muh Wage Gap: both aren't big fans of humanity since... They're Alphas. But the Servorum kinda realize that they have to put up with humans, and try not to fuck with them too much
> But Muh Wage Gap: Dominion decides to help the Mil'taj fuck them up though
> But Muh Wage Gap: since they want revenge
> But Muh Wage Gap: ye
> Derpy Horse: So the Dominion are more offense oriented while the Servorum are more defense oriented.
> But Muh Wage Gap: yes
> Derpy Horse: Now I'm thinking that the Dominium should have most of their current ships be T1.1, explained as being mass produced for the sake of war and therefore aren't the best, and then the Kukri + their unreleased ships could be T2 ships that are rarer but far greater than their normal stuff. And the Servorum, worried more about just getting by, would be T1.5 since they aren
> Derpy Horse: 'aren't too worried about developing better technology but also aren't pumping out low end ships
> Derpy Horse: The reason I want the Dominion to have some lower end ships is because of their proximity to human space; I feel like it makes sense that the Humans would hold out if they were only fighting T1.1 ships most of the time
> But Muh Wage Gap: right
> But Muh Wage Gap: i see what you're saying
> But Muh Wage Gap: the majority of their ships are meh, but then they have Trump™ cards
> Derpy Horse: Yup.
> But Muh Wage Gap: like the Kukri
> But Muh Wage Gap: and the BATTLESTAR™
> Derpy Horse: mhm.
> But Muh Wage Gap: and FTek™ capitalism helping their economy

**Comment by Amazinite** [comment]
Want the Tuk'ux to be T3?

**Comment by Amazinite** [comment]
Equations I'm using to balance. This mainly applies to combined hit points.

T(x) Fighter = T(x) Light Warship \* 0.2
T(x) Medium Warship = T(x) Light Warship \* 2
T(x) Heavy Warship = T(x) Light Warship \* 4
T(x+1) Light Warship = T(x) Heavy Warship

**Comment by Amazinite** [comment]
Closing because this was pretty much moved to the project notes.
