### ISSUE TITLE
Remove FTek from outfit and ship names?

### ISSUE THREAD

**Issue by Amazinite** [Amazinite/Shields-Up#31]
And leave it in the description. Just thinking this because it's not like things are names the "Lionheart Bactrian" or "Kraz Flamethrower."

Might end up having a reverse compatibility issue if we don't leave everything an old version, but I'm not one to care about those much, especially in the event of name changes.

**Comment by Amazinite** [comment]
Might end up having a reverse compatibility issue, but I'm not one to care about those much, especially in the event of name changes.

**Comment by FriendlyNeighbour** [comment]
How could I have passed up the opportunity to cement my legacy?!?! Let teh FTek name stay! (/ o o)/

**Comment by Amazinite** [comment]
Aight o3o
