### ISSUE TITLE
Choose which is which

### ISSUE THREAD

**Issue by Amazinite** [Amazinite/Shields-Up#34]
Which one do you want to be the Active Blaster and which one do you want the Heavy Blaster. I can do recolorings if you want, too.

![ftek blaster 2 pp](https://cloud.githubusercontent.com/assets/17688683/17856531/00f1d1d6-684c-11e6-9bfd-74b690d7895c.png)
![ftek blaster 1 pp](https://cloud.githubusercontent.com/assets/17688683/17856533/027d10f6-684c-11e6-9292-b38b8cefc99f.png)

**Comment by FriendlyNeighbour** [comment]
Top one heavy, bottom one active. Perhaps change them to be the same colour that the current ones are? ie: Heavy is orange and Active is red.

**Comment by Amazinite** [comment]
Will do.

**Comment by Amazinite** [comment]
dde5e52
