### ISSUE TITLE
An issue on ship and outfit images

### ISSUE THREAD

**Issue by Amazinite** [Amazinite/Shields-Up#35]
I'm just going to post stuff here that we may or may not use to replace missing/duplicate ship and outfit images.

**Comment by Amazinite** [comment]
![legionaire](https://cloud.githubusercontent.com/assets/17688683/18413327/92ab9b22-7772-11e6-80d7-4d359dc8c282.png)

**Comment by Amazinite** [comment]
Legionaire
![legionaire](https://cloud.githubusercontent.com/assets/17688683/18413321/6af69212-7772-11e6-9942-1c70dd0f2104.png)
You like?
It's really just a mostly symmetrical Mule.

Edit: Might add some extra fins in the back.

**Comment by FriendlyNeighbour** [comment]
That looks sexy as hell.

**Comment by Amazinite** [comment]
Better.
![legionaire](https://cloud.githubusercontent.com/assets/17688683/18453653/51872e84-790e-11e6-842f-634ece917f21.png)

**Comment by Amazinite** [comment]
Mil'taj Point Defense Turret
![point defence](https://cloud.githubusercontent.com/assets/17688683/18454441/6c40603e-7912-11e6-9fb5-d1b346a96b86.png)
Because why not.

**Comment by Amazinite** [comment]
Pirated Frigate
![pirate frigate](https://cloud.githubusercontent.com/assets/17688683/18457060/b41ee54a-7923-11e6-8367-aff59604548e.png)

**Comment by Amazinite** [comment]
Original, Shields Up, Revamped

Legionaire
![comparison mule](https://cloud.githubusercontent.com/assets/17688683/18457204/ae96e1da-7924-11e6-9f64-cee994dca0e0.png)

Pirate Frigate
![comparison frigate](https://cloud.githubusercontent.com/assets/17688683/18457200/a8049b32-7924-11e6-83a2-4fa989f5eda8.png)

**Comment by Amazinite** [comment]
Do you want me to remake all of the current (human) ships in Blender? That way we'll have .blend files for easy modifications and also be able to keep everything looking like the vanilla graphics. (I'm looking at you, Ironclad Carrier.)

**Comment by Amazinite** [comment]
Vagabond: Clipper and Firebird mashup
Skybus: ???
Archangel: The back is part of the Star Queen, the front is part of the Bounder, but what's that middle section made from?

**Comment by Amazinite** [comment]
**Hauler XV**: Shit ton of Hauler containers.

**Comment by Amazinite** [comment]
**FTek Destroyer**: Cockpit is Frigate, midsection is Cruiser

**Comment by Amazinite** [comment]
**Skybus**: Firebird bits, Frigate cockpit glass as entire cockpit?
**Archangel**: Middle section is Dreadnought.

**Comment by FriendlyNeighbour** [comment]
Skybus: Unknown ~ designed by Direstorm
FTek Destroyer: Cockpit is from Frigate, mid section is from Cruiser
Archangel: mid section of Archangel is from Dreadnought
Spearhead: Yes. Deal with it.
Ironclad Carrier: front half of carrier is the engine section of the Republic Cruiser
Ironclad Battleship: cockpit is from Frigate

**Comment by Amazinite** [comment]
**Ironclad Carrier**: Cockbit might be edited Aerrie.

**Comment by Amazinite** [comment]
HaulerXV
![hauler xv](https://cloud.githubusercontent.com/assets/17688683/18611332/ae216990-7d03-11e6-989c-52b925fd4916.png)

**Comment by Amazinite** [comment]
A version that stays true to the "xv."
![hauler xv 2](https://cloud.githubusercontent.com/assets/17688683/18617550/1ecbcc70-7da0-11e6-98c9-984617cd346d.png)

6 of the containers are under, 6 over, 3 in the middle section.

**Comment by Amazinite** [comment]
Draft Vagabond,
![vagabond](https://cloud.githubusercontent.com/assets/17688683/18812590/57269116-82a7-11e6-90c4-21c57bd1ec0e.png)
Want to do more to it to make it look less like the Clipper.

**Comment by Amazinite** [comment]
Skybus
![skybus](https://cloud.githubusercontent.com/assets/17688683/18812657/61f43c86-82a9-11e6-82e3-b36f39faf424.png)

**Comment by Amazinite** [comment]
FTek Destroyer
![destroyer](https://cloud.githubusercontent.com/assets/17688683/18815904/82727826-830b-11e6-8b11-535671b2644a.png)

**Comment by Amazinite** [comment]
Different Vagabond; color swap and some engine bits.
![vagabond](https://cloud.githubusercontent.com/assets/17688683/18816000/b5b48b64-830d-11e6-991f-cb94a30fbd53.png)

**Comment by Amazinite** [comment]
Vagrant
![vagrant](https://cloud.githubusercontent.com/assets/17688683/18817009/7d809240-8323-11e6-88ac-1c45e026979e.png)

**Comment by Amazinite** [comment]
Archangel
![archangel](https://cloud.githubusercontent.com/assets/17688683/18817684/d446f90a-8334-11e6-9406-68aa9975fc9b.png)

**Comment by FriendlyNeighbour** [comment]
These. Are. Beautiful. Also, is there a way to have Github notify me when stuff gets posted?

**Comment by Amazinite** [comment]
Do you see the buttons on the top right that say "watch, stars, forks?" Click watch and you'll be sent an email every time someone comments here.

**Comment by Amazinite** [comment]
Derelict
![derelict](https://cloud.githubusercontent.com/assets/17688683/18854844/3b064ae6-841c-11e6-8251-2bcb1503d5b9.png)

**_Ships to do:_**
~~**Legionaire**: Modified Mule~~ https://github.com/Amazinite/Shields-Up/issues/35#issuecomment-246499949
~~**Pirate Frigate**: Modified Frigate~~ https://github.com/Amazinite/Shields-Up/issues/35#issuecomment-246533058
~~**Vagabond**: Clipper and Firebird mashup~~ https://github.com/Amazinite/Shields-Up/issues/35#issuecomment-249425948
~~**Vagrant**: Looks like part Clipper, part Firebird, part Star Barge, part Rainmaker~~ https://github.com/Amazinite/Shields-Up/issues/35#issuecomment-249434213
~~**Skybus**: Firebird bits~~ https://github.com/Amazinite/Shields-Up/issues/35#issuecomment-249398942
~~**FTek Destroyer**: Cockpit is Frigate, front is freighter, midsection is Cruiser, engines are Star Queen~~ https://github.com/Amazinite/Shields-Up/issues/35#issuecomment-249425050
~~**Archangel**: Front is Bounder, midsection is Dreadnought, engines are Star Queen~~ https://github.com/Amazinite/Shields-Up/issues/35#issuecomment-249441311
~~**Derelict**: Mainly Leviathan, some Mule, and random other bits~~ https://github.com/Amazinite/Shields-Up/issues/35#issuecomment-249723252
**Ironclad Carrier**: Back is Aerie, midsection is Cruiser engine section, front possibly Aerie?
**Ironclad Battleship**: The engines are from the Firebird, the middle section and drone hangars are from the Carrier, and I'm not sure about the cockpit
~~**Hauler XV**: Bunch of Hauler containers.~~ https://github.com/Amazinite/Shields-Up/issues/35#issuecomment-247814252

**_Ships using vanilla sprites:_**
**Modified Firebird**
**Sky Dinghy**
**Switchblade**

**ARE:**
~~**Thorn**: Carrier/Cruiser mashup~~ Leaving out since it's part of ARE and doesn't look too bad. Just needs some post processing.
**Spearhead**: A Splinter with two combat drone stuck to it. Really? (Actually doing this cus it sucks)

**Comment by Amazinite** [comment]
**Samurai:** Engines are cruiser, right and left sections are Protector, and midsection is cruiser bits. Front midsection is a Hauler crate, to the right and left of that Hauler crate are Frigate rears, and to the right and left of those are Firebird wings with guns attached. The cockpit is a Bulk Freighter cockpit with Firebird wings on either side.

As for the Phoenix, it's ugly as is, so I'm not making a recreation of its current sprite. I'd rather take the description into mind and create a heavy warship version of the Firebird.

Will be fun.

**Comment by FriendlyNeighbour** [comment]
Outfits that are either missing or need work in terms of images

Guns:
FTek Homing blaster uses a slightly altered Hai Pulse Cannon
Particle Accelerator uses Particle Cannon image

Turrets:
FTek Blasters use slightly altered Regular Blaster image
Mil’taj Point Defence uses Hai Pulse Turret image
Mil’taj Anti-Missile Turret uses Heavy Anti-Missile

Secondary Weapons: All have images

Ammunition: All have images

Systems:
“Hal-500” Automation Matrix has no image
AI Mainframe has no image
FTek Bot Shelf has no image
Heavy Rocket Depot has no image
Hervar Regenerator has no image
Intelligent Rocket Depot has no image
Meteor Missile Depot has no image
Nalabidium Heat Sink has no image
Pillager Bolt-on Cockpit could use some work
Sidewinder Missile Depot has no image
Signal Interdictor Deluxe has no image
Soaker Missile Depot has no image
Torpedo Supply Depot has no image
XF-111 Ship Core, XF-333 Ship Core, XF-555 Ship Core have same image

Power:
Mil’taj Curtana Battery and Mil’taj Condensed Battery using Small Biochemical Cell
Mil’taj Cooling Cell and Unit both using Dwarf Core
Mil’taj Grey and Black Generators are both using some sub-par images

Engines:
Polaric Slide Thrusters has no image

Hand to Hand:
Breacher Cannon can use some work
FTek UMDB has no image
Hai Crew Member has no image
R-120 Warbird has no image
S-45 Lamprey has no image
Sentry Gun has no image
Ship Armory has no image
Special Agent has no image
Tactical Armor could use some work
Wanderer Crew Member has no image

Special:
Crew Card has no image
Engineer Bot has no image
Repair Bot has no image
Sizeable Map uses Local Map image

**Comment by Amazinite** [comment]
@Disiuze Burn the alien crew outfits.

**Comment by Amazinite** [comment]
Added the new Legionnare image. Going to post process and add the rest that I have so far, then worry about doing the Samurai and probably thinking of a new design for the ugly-ass Phoenix.

**Comment by Disiuze** [comment]
@FriendlyNeighbour 

> Everything on systems minus the FTek Bot shelf

I was planning to do them but never had the time

> Polaric Slide Thrusters

They shouldn't even be available as they can't do what Tufton intended them to do.

> Hand2Hand things I made

See systems.

> Special

For bots and cards see systems, Sizeable Map uses Local Map image because I couldn't be bothered to and thought it would work.

@Amazinite 
I wil

**Comment by Amazinite** [comment]
I had an idea for the bot outfits earlier: take the android outfit and change it to be holding things like screwdrivers, a laser rifle, etc. depending on the bot's purpose.

**Comment by Amazinite** [comment]
bd83fe9

Ships to do:
**Ironclad Carrier**: Back is Aerie, midsection is Cruiser engine section, front possibly Aerie?
**Ironclad Battleship**: The engines are from the Firebird, the middle section and drone hangars are from the Carrier, and I'm not sure about the cockpit.
**Samurai:** Engines are cruiser, right and left sections are Protector, and midsection is cruiser bits. Front midsection is a Hauler crate, to the right and left of that Hauler crate are Frigate rears, and to the right and left of those are Firebird wings with guns attached. The cockpit is a Bulk Freighter cockpit with Firebird wings on either side.

**_Ships using vanilla sprites:_**
**Modified Firebird** (Make into freighter)
**Sky Dinghy**
**Switchblade**

**Comment by Amazinite** [comment]
How's this look for a draft ship armory that I spent like 3 minutes on?
![armory](https://cloud.githubusercontent.com/assets/17688683/19667748/b0d8dbb6-9a20-11e6-90cc-e5985076b171.png)

**Comment by Amazinite** [comment]
New gun lookin thing.
![laser smg](https://cloud.githubusercontent.com/assets/17688683/19668268/9176115e-9a24-11e6-8a8a-6f3f546e3dea.png)

**Comment by Kryes-Omega** [comment]
noice

**Comment by Disiuze** [comment]
The armoury looks exactly what I'd image it'd look like.

**Comment by Amazinite** [comment]
Going to do some of the different bots tonight. 

We should also remove tactical armor, because if we implement Phil's mod then there'll be two types of armor (tactical and military).

**Comment by Amazinite** [comment]
Better
![armory](https://cloud.githubusercontent.com/assets/17688683/19702460/c4d58b7a-9acd-11e6-9b70-cf61780f0ef9.png)

**Comment by Amazinite** [comment]
Repair bot
![engineer android](https://cloud.githubusercontent.com/assets/17688683/19703054/5ab28b5a-9ad0-11e6-839b-a65396ca7541.png)
Warbird
![boarding android](https://cloud.githubusercontent.com/assets/17688683/19703055/5c66788a-9ad0-11e6-8bb4-ca58b49287ae.png)

**Comment by Amazinite** [comment]
This is fun.

**Comment by Amazinite** [comment]
_*Ships to do:*_
**Ironclad Carrier**: Back is Aerie, midsection is Cruiser engine section, front possibly Aerie?
**Ironclad Battleship**: The engines are from the Firebird, the middle section and drone hangars are from the Carrier, and I'm not sure about the cockpit.
**Samurai:** Engines are cruiser, right and left sections are Protector, and midsection is cruiser bits. Front midsection is a Hauler crate, to the right and left of that Hauler crate are Frigate rears, and to the right and left of those are Firebird wings with guns attached. The cockpit is a Bulk Freighter cockpit with Firebird wings on either side.

**_Ships using vanilla sprites:_**
**Modified Firebird** (Make into freighter)
**Sky Dinghy**
**Switchblade**

_*Outfits to do:*_

**Comment by Amazinite** [comment]
Lamprey, meant more for defense than the Warbird.
![lamprey](https://cloud.githubusercontent.com/assets/17688683/19786184/b40c2a44-9c6a-11e6-8699-894aa040b0f9.png)

**Comment by Amazinite** [comment]
Engineer bot; really just a repair bot color swap.
![engineer bot](https://cloud.githubusercontent.com/assets/17688683/19786409/d0dbb436-9c6b-11e6-8404-5a49fefab5ab.png)

**Comment by Amazinite** [comment]
Archangel
![archangel](https://cloud.githubusercontent.com/assets/17688683/19832791/42d32e3a-9dfb-11e6-88bd-1c0d808c48d4.png)

More armored Warbird
![warbird](https://cloud.githubusercontent.com/assets/17688683/19832812/a9d8dfd0-9dfb-11e6-8909-edc516c45f29.png)

**Comment by Amazinite** [comment]
Outfits I think we should deprecate:

**Specials**
Crew Card

**H2H**
Special Agent, Toaster Bot, FTek UMDB, Sentry Gun, Breacher Cannon, Tactical Armor, "Rock Wall"

**Engines**
Polaric Slide Engines

**Systems**
FTek Bot Shelf

**Weapons**
Rail Cannon

**Comment by Amazinite** [comment]
Doing what I want with deprecation now.

**Comment by Amazinite** [comment]
395fdcc

**Comment by Amazinite** [comment]
**Ships to do**
Ironclad Carrier: Back is Aerie, midsection is Cruiser engine section, front possibly Aerie?
Ironclad Battleship: The engines are from the Firebird, the middle section and drone hangars are from the Carrier, and I'm not sure about the cockpit.
Samurai: Engines are cruiser, right and left sections are Protector, and midsection is cruiser bits. Front midsection is a Hauler crate, to the right and left of that Hauler crate are Frigate rears, and to the right and left of those are Firebird wings with guns attached. The cockpit is a Bulk Freighter cockpit with Firebird wings on either side.
Modified Firebird: Currently using Firebird sprite. (Make into freighter)
Sky Dinghy: Currently using Shuttle sprite.
Switchblade: Currently using Dagger sprite.

**Outfits to do (first)**
FTek Heavy Blaster Turret
FTek Active Blaster Turret
Particle Accelerator
400mm Mag Rail Canon
EMP Bomb Launcher
Hedgehog Ion Mine Laucher
Intelligent Rocket Launcher
1 Ton Shell
Automation Matrix
AI Mainframe
Interference Hull and Shielding
Shield Capacitors (5)
Skylance Rifle + Rifle Rack
Ship Cores (3)
FTek Capacitor
FTek021 Rechargable Battery
RCS Engines (2)
Expanded Map and Sizeable Map

**Comment by Amazinite** [comment]
Mod Firebird
![mod firebird render](https://cloud.githubusercontent.com/assets/17688683/20247395/2ece9b46-a999-11e6-96bc-f60860d9965d.png)

**Comment by Amazinite** [comment]
Remove the Spearhead?

**Comment by Amazinite** [comment]
Removed it.

**Comment by Amazinite** [comment]
**Ships to do**
Ironclad Carrier: Back is Aerie, midsection is Cruiser engine section, front possibly Aerie?

Ironclad Battleship: The engines are from the Firebird, the middle section and drone hangars are from the Carrier, and I'm not sure about the cockpit.

Samurai: Engines are cruiser, right and left sections are Protector, and midsection is cruiser bits. Front midsection is a Hauler crate, to the right and left of that Hauler crate are Frigate rears, and to the right and left of those are Firebird wings with guns attached. The cockpit is a Bulk Freighter cockpit with Firebird wings on either side.

~~Modified Firebird: Currently using Firebird sprite. (Make into freighter)~~ https://github.com/Amazinite/Shields-Up/issues/35#issuecomment-260198297

Sky Dinghy: Currently using Shuttle sprite.

Phoenix: Looks like crap right now. Make it an actual heavy-warship version of the Firebird.

**Outfits to do (first)**
~~FTek Heavy Blaster Turret~~ cff47cb
~~FTek Active Blaster Turret~~ cff47cb
Particle Accelerator
400mm Mag Rail Canon
EMP Bomb Launcher
Hedgehog Ion Mine Laucher
Intelligent Rocket Launcher
1 Ton Shell
Automation Matrix
AI Mainframe
Interference Hull and Shielding
Shield Capacitors (5)
Skylance Rifle + Rifle Rack
Ship Cores (3)
~~FTek Capacitor~~  cff47cb (temporary)
FTek021 Rechargable Battery
RCS Engines (2)
Expanded Map and Sizeable Map

**Comment by Amazinite** [comment]
Given that this issue is outdated, I'm going to close it and reopen a new issue once I learn more Blender to be able to actually do most of these things and make them look original.
