### ISSUE TITLE
Goals for the next release?

### ISSUE THREAD

**Issue by Amazinite** [Amazinite/Shields-Up#36]
What do you want to get done before releasing a new version? 
I'd say at the very least we should resolve the current issues, possibly also going into some preliminary rebalancing of the races as well.

**Comment by FriendlyNeighbour** [comment]
We need to make images for the outfits currently missing images. Rebalancing the races is definitely something we need to go into as well.

**Comment by Amazinite** [comment]
Set up a [project](https://github.com/Amazinite/Shields-Up/projects/1) with a to do list.

**Comment by Amazinite** [comment]
Going to close this since the issues that need addressed are either in the project or attached to their own issue.
