### ISSUE TITLE
Mule cost was increased in base game.

### ISSUE THREAD

**Issue by Amazinite** [Amazinite/Shields-Up#37]
The hull was given +2 million cost.
Shields Up gives it a +3 million cost (from current in v0.9.3).
Increase the cost again relative to the vanilla version or just get rid of the cost increase because of the vanilla change?

**Comment by FriendlyNeighbour** [comment]
We should get rid of the increased cost Shields Up gives it.

**Comment by Amazinite** [comment]
How about the Bactrian? Doesn't that have a cost increase?

**Comment by FriendlyNeighbour** [comment]
I don't believe so.

**Comment by Amazinite** [comment]
```
ship "Bactrian"
    licenses
        "Deep Sky"
    attributes
        "cost" 18600000
```

**Comment by FriendlyNeighbour** [comment]
I stand corrected. I would get rid of the price change, but perhaps keep the license requirement? The license is given after campaign. What do you think about that?

**Comment by Amazinite** [comment]
I think that's fair.
