### ISSUE TITLE
Possible lore tweak.

### ISSUE THREAD

**Issue by Amazinite** [Amazinite/Shields-Up#38]
So we know that the Alphas receive outfits from the Mil'taj. Seeing as how Mil'taj outfits are suppose to be T2.5, fitting the Dominion's main T1.1 ships with Mil'taj gear will make them far more superior to human ships than they probably should be. Suggested tweak lore to make it so that the Alphas don't exactly have an unlimited number of Mil'taj outfits and thus save (most) of their Mil'taj outfits for their T2 ships, using instead human outfits (or even modified human outfits) on a bulk of their T1.1 ships. 

Maybe also give Servorum their own outfits, explained as them not wanting to accept outfits from the Mil'taj who seek the destruction of Humanity.

**Comment by Amazinite** [comment]
Also, Tuk'ux T3?

**Comment by FriendlyNeighbour** [comment]
Seems like a wise decision.

**Comment by Amazinite** [comment]
Closing because this was moved to the project notes.
