### ISSUE TITLE
Anything that changes the stats of vanilla outfits

### ISSUE THREAD

**Issue by Amazinite** [Amazinite/Shields-Up#4]
I want to remove it.

Offending files so far:
Shields Up/data/power.txt

**Comment by FriendlyNeighbour** [comment]
I suppose it would be better to remove it, although in doing so it may be wise to decrease the strength of our modded energy systems and the modded weapon's requirements (particularly the Alpha outfits) so they are a bit more scaled.

**Comment by Amazinite** [comment]
See #7.

**Comment by Amazinite** [comment]
Removing it for now; will do a rebalancing patch later. b24a9ed
