### ISSUE TITLE
Tribute

### ISSUE THREAD

**Issue by Amazinite** [Amazinite/Shields-Up#41]
A lot of planets need tributes to them.
Also possibly do that event idea where dominating a planet of an alien race triggers that planet to sell at the very least outfits. Capital planets may also give shipyard privileges when dominated.

**Comment by FriendlyNeighbour** [comment]
Also, the income given by the Dominion planets right now seems a bit excessive. I may have to lower those, what are your thoughts on that?

**Comment by Amazinite** [comment]
I don't know right now, but we'll have to adjust them anyways after the Dominion rebalance.

**Comment by Amazinite** [comment]
Removed tribute on all planets. Going to worry about this later.

**Comment by Amazinite** [comment]
Tribute is a serious story breaker, which is probably why it's only available in human space in the vanilla game. Unless that changes, I'm going to keep that the same in SU.
