### ISSUE TITLE
Remove shortcuts in vanilla map?

### ISSUE THREAD

**Issue by Amazinite** [Amazinite/Shields-Up#43]
Wormholes included. 
1) The map was made the way it is for a reason.
2) Wormholes are suppose to be rare; the base game only has 3. 2 of which are story related and created later on.
3) We already removed other stuff that changed the vanilla outfit and ship stats, why not remove the changes to the vanilla map?

Stuff like slightly moving a few of the eastern and south eastern systems can stay, but the rest should go back to normal.

**Comment by Disiuze** [comment]
Agreed. It also make mods that add stuff in human space at shortcut locations incompatible with SU.

**Comment by spiral03** [comment]
The current map config for SU is a little heavy on the wormholes.  Perhaps if some of them could be hidden behind missions involving the Mil'taj or Tuk'ux.

**Comment by Amazinite** [comment]
I believe that the last two commits (5bb7c30 and 909c998) address this. Shortcut systems have been removed and the only wormhole reachable in human space now is the Hai wormhole. Friendly and I decided to keep the shortcut area to the west that connects the entrance to the Deep and the back of the Free Worlds, for now at least.
