### ISSUE TITLE
Outfit Redundancies

### ISSUE THREAD

**Issue by spiral03** [Amazinite/Shields-Up#44]
There are two Railguns, and one of them has stats that are superior to the other one in every way.  The ship bots from all the different expansions that all use completely different game mechanics are confusing to players and clutter the outfitter.  Some of the weapons added are rendered useless by the other weapons that have been added.  Weapon/Engine specializations give you twice as much space as they require?  Mass expansions cost 20 cargo space and give back 15 outfit space.  I would expect for the Weapon/Engine specializations to work similarly.

Solutions: 
Remove one of the Railguns or remake it to fill a different role.
                 Remove some ship bots or remake them.  I think we're allowed to use the 'automated capture' attribute now
                 Remove some weapons and rebalance others.

Happy to volunteer, just need permission first :)

**Comment by Amazinite** [comment]
Yeah, perfect compatibility between all mods is coming after each mod is fine within itself, and rebalancing is a work in progress right now. 

For now, do you think you could make a list of name for the outfits that are redundant and the mods they come from?

Ideally I'd like to keep most things, just have them be more unique from one another, but some stuff (like the two different bot systems) may need to be removed.

**Comment by spiral03** [comment]
On it ^.^

**Comment by spiral03** [comment]
https://github.com/spiral03/Shields-Up/blob/master/redundancies.txt

Also, the Mil'taj and Tuk'ux can't agree on which one of them invented the Shield Decimator.  I vote for the Tuk'ux using a homing projectile version, which I would be happy to whip up.

**Comment by Amazinite** [comment]
Speaking of the two alien species, why does everyone hate the Quarg?
The Tuk'ux hate the Quarg, the Mil'taj hate the Quarg, the Alphas hate the Quarg. What do you have against the Quarg, @FriendlyNeighbour?

_low-key making a new alien race in my mod that hate the Quarg._

Edit: I have no idea why Pompano has the Tuk'ux hate the Quarg, but the Alphas make sense already and the Mil'taj have their backstory.

**Comment by Amazinite** [comment]
Given that there is now a .txt file to track redundancies, I think it's safe to close this.
