### ISSUE TITLE
Get rid of Modified Firebird?

### ISSUE THREAD

**Issue by Amazinite** [Amazinite/Shields-Up#47]
It's really nothing more than what the Marauders are right now.
Or we could make it like a Modified Argosy and give it a different purpose, maybe making it a high end freighter of sorts.

**Comment by FriendlyNeighbour** [comment]
maybe giving it a different purpose.

**Comment by Disiuze** [comment]
A freighter which can defend itself fairly well would be a good repurpose, I guess.

**Comment by Amazinite** [comment]
Noted on #35
