### ISSUE TITLE
Phil's Flavours

### ISSUE THREAD

**Issue by Phil-Morley** [Amazinite/Shields-Up#49]
Hi,

I'm working on compatibility between Phil's Flavours (I need to think of a better name :) and shields up, which with the exception of fleets (which need redoing anyway) has been surprisingly easy. 

The main problem I see with my mod is that beyond adding a lot of new ships to play with there is no real reason to use it in that it has no new story or places to explore etc. Every time I go to write some I end up just drawing new ships :) 

If you are agreeable I'd like to fully integrate my mod and just have it as part of shields up and abandon it as a standalone?

**Comment by Amazinite** [comment]
Sounds great. When do you want to integrate it though? As soon as possible or wait until you get things polished up and finished? Because I'd love to have you aboard, but I know that your mod has a bunch of errors in it, like the fact that I've seen a few Republic fleets with your ships where certain ships seem to have no power or are just overheated so they just drift on forever.

**Comment by Phil-Morley** [comment]
Cool. When it is polished and finished (too much of a rush to get it online - I have found a number of other errors too). As well as other tweaks, there are way to many variants which is also leading to fleets being ridiculous, so I will redo it and bring down to about 2-3 variants of each and then redo fleets. Should be late next week or so

**Comment by Amazinite** [comment]
It's almost been a month; do you think you're close to being ready?

**Comment by murrayvb0** [comment]
He said in steam forum that he's been busy with work lately. https://steamcommunity.com/app/404410/tradingforum/348292957933722132/?ctp=2

**Comment by Phil-Morley** [comment]
Hi,
1 or 2 small fixes from the one on steam and it is pretty much ready, which will have to start with questions. Use next directory - 007 or is another that you would prefer?
fleets will have to be redone, should I do this?

**Comment by Amazinite** [comment]
It should start with 007 and if by redo fleets you mean make them compatible with Shields Up and Alphean, I'll take care of that.

**Comment by Phil-Morley** [comment]
Great!

**Comment by Amazinite** [comment]
2fe4bb6
I'll start working on fleet compatibility a bit later.
