### ISSUE TITLE
Remove FTek bot outfits and just use ARE bots?

### ISSUE THREAD

**Issue by Amazinite** [Amazinite/Shields-Up#53]
There's really no point for the FTek bots when the ARE bots are there and more fleshed out.

**Comment by Amazinite** [comment]
Related: remove the P-75 Archangel? It's a Penum robot, but seeing as how the Penum was removed, I think it would make sense to remove it.

**Comment by Disiuze** [comment]
I think it's better to just rename it (I'm going to reuse it for the Federation, but feel free to remove it as that won't happen for some time).

**Comment by Amazinite** [comment]
I'll make it a grenadier bot, since the other two have guns.

**Comment by Amazinite** [comment]
I'm going with yes. I've moved the topic over to 35
