### ISSUE TITLE
extended interceptor intro

### ISSUE THREAD

**Issue by Mark4666** [Amazinite/Shields-Up#54]
In the final mission where you take Paul to Amazon the mission places a waypoint in Hamal now that the Pi Capuli system has been removed it forces you to take a longer journey with no clear purpose.
![image](https://cloud.githubusercontent.com/assets/22483942/19718537/a958720a-9b5d-11e6-8b27-d9d80fcfd641.png)

**Comment by Mark4666** [comment]
He also mentions the Pi Capuli system after you accept the "Ext Intro [Interceptor 2]" mission.

**Comment by Amazinite** [comment]
Good catch. I think this mission was originally made by either @FriendlyNeighbour or Direstorm, so Friendly should probably take care of it. 

Edit: Why do those missions even have waypoints in the first place? It makes you required to go to them to complete the mission, which makes no sense given their unimportance to the mission itself.

**Comment by Mark4666** [comment]
Copied and pasted all mentions Paul makes of waypoints and referenced their source missions .

"Ext Intro [Cargo 2]"
Once inside your ship, Paul turns to you, "Make sure you avoid heading too far east of here, all those systems are uninhabited, wouldn't want to get stuck with no fuel. To help you avoid the systems I'll set some waypoints on you ship's map to avoid any... unfortunate accidents."

"Ext Intro [Interceptor 2]"
"Awesome! Like I said, it's a little ways away, so I'll set you some waypoints on your map to help you out." He pauses. Then adds: "Oh, and Captain... On your way to Canyon, if you pass through the Pi Capuli system, you'll pass by a wormhole. I would advise you stay away from it. Who knows where it might lead."

"Ext Intro [Interceptor 4]"
"Thank you, you have no idea how helpful you've been to me. I've also set some waypoints to point you in the right direction."

"Ext Intro [Transport 2]"
"Great! Thank you so much for helping! I'll have those waypoints set to guide you to Matar."

**Comment by Amazinite** [comment]
Thanks.

**Comment by Mark4666** [comment]
list of all waypoints in the Paul mission chains and their respective missions. 

"Ext Intro [Cargo 2]"
waypoint "Phact"
waypoint "Aldebaran"
waypoint "Diphda"

"Ext Intro [Interceptor 2]"
waypoint "Alhena"
waypoint "Capella"
waypoint "Sirius"
waypoint "Caph"
waypoint "Ankaa"
waypoint "Sheratan"

"Ext Intro [Interceptor 4]"
waypoint "Hamal"
waypoint "Alpheratz"

"Ext Intro [Transport 1]"
waypoint "Betelgeuse"

"Ext Intro [Transport 2]"
waypoint "Wazn"
waypoint "Acamar"
waypoint "Markab"

**Comment by Amazinite** [comment]
I've removed the waypoints in a152d44, but Paul still mentions them in the mission text. @FriendlyNeighbour should fix that.

**Comment by FriendlyNeighbour** [comment]
Done. 2bf6537
