### ISSUE TITLE
Lock androids/bots behind a quest

### ISSUE THREAD

**Issue by Amazinite** [Amazinite/Shields-Up#55]
MZ removed androids for a reason; they're powerful outfits that don't make much sense to be tier 1 outfits. As such, I think we should lock all AI/bot/android outfits behind a quest of some sorts, likely involving the Deep and/or the Kor automatons.

**Comment by Disiuze** [comment]
Agreed, maybe a chain for each type of bot so it feels like takes time to develop.

**Comment by Amazinite** [comment]
I was thinking first the development of the AI Mainframe and normal androids that reduce crew (removing the current Crew Card outfit) and then do more missions to develop the ~~two~~ three combat and two mechanic bots.

E: the final thing to be unlocked would be the automation matrix.

**Comment by Amazinite** [comment]
What do you think about giving the combat and mechanical androids `"required crew" 1` and `bunks 1` so that they act as actual crew in the case of boarding, and cost "salaries" as maintenance costs on the androids or materials needed for repairs and ammunition? Not sure how that would work out mixing normal androids and specialized androids, though.

In the end, maybe we should just remove required-crew reducing outfits. 

Edit: Yeah, we should ditch the androids that reduce crew capacity and instead go with only the automation matrix. That way you wouldn't have the problem with mixing androids, since you wouldn't be able to pilot your own ship to board people with the matrix installed (I think).

Edit: #56 Yup

**Comment by Phil-Morley** [comment]
Possibly the same for Skylance rifles? they are cool and I see their value but have 1-2 mid game makes you very overpowered for capturing human ships, perhaps they should only be available on a some planets that require jump drive or some similar limiter?

**Comment by Amazinite** [comment]
As of right now, I have the Dominion ships using androids, and their ships have built in bot capacities. Whatever quest happens to lock androids, it should probably relate to the Dominion.

**Comment by Amazinite** [comment]
The Skylance Rifles will also eventually get some sort of quest, but that's part of Pompano's mod so it's really up to him at this point.

**Comment by Amazinite** [comment]
Outsourced to a card in the `To do or consider` column of the [roadmap project](https://github.com/Amazinite/Shields-Up/projects/1).
