### ISSUE TITLE
Cannot use "HAL-500" Automation Matrix on flagship

### ISSUE THREAD

**Issue by magao** [Amazinite/Shields-Up#56]
If the flagship has zero crew then you cannot depart the planet (button missing) and if you restart the game the next ship in your fleet will be selected as the flagship.

To instead have a crew of 1, set the required crew to a ridiculously high negative number e.g.

```
"required crew" -1000000
```

Unless of course the intention is that the automation matrix shouldn't be usable on the flagship (it's not clear, but reading other issues implies that might be the case).

**Comment by Amazinite** [comment]
This is intended behavior. The automaton attribute on a ship means that the ship is entirely controlled by an AI, meaning that the ship has no crew and you yourself can not pilot it. If you wish to reduce your crew requirement for your flagship, buy one of the NDR-114 Androids or an AI Mainframe and some crew cards.
