### ISSUE TITLE
FTek shield systems vs shield capacitors

### ISSUE THREAD

**Issue by Amazinite** [Amazinite/Shields-Up#6]
The FTek shield systems and SC-whatever- shield capacitors both do the exact same thing and are both included in SU. Either remove one or change one to be different.

**Comment by Disiuze** [comment]
I modelled mine after batteries, and I think I balanced them quite well.
I had a talk about them in the past with Friendly and the outcome was to keep both.

**Comment by Amazinite** [comment]
Then one should probably get something to it to differentiate the two. Maybe give the FTek versions less shield buff per ton of mass, but at the same time charge shields. That way if you want straight up shield buff you'd go for the shield capacitor, but if you want to worry more about recharging the shields that you have then the FTek version would be better.

**Comment by FriendlyNeighbour** [comment]
Yeah, I agree on this. FTek could get the extra shield recharge, and the SC could get the extra shield power.

**Comment by Disiuze** [comment]
I rebalanced mine: all shield capacity of the SCXXs series was multiplied by 1.5.
