### ISSUE TITLE
ARE Mega Ships?

### ISSUE THREAD

**Issue by Amazinite** [Amazinite/Shields-Up#60]
I get the Kreig, but what about the Capitalis and MMMXV?

**Comment by Disiuze** [comment]
Capitalis is more of a practical decoration, it's flagship of Tarazed.
The MMMXV was supposed to be the Syndicate Flagship but I never really got around to working on it.

**Comment by Amazinite** [comment]
So what are you going to do with them for now?

**Comment by Disiuze** [comment]
Planning on using them in the coming Federation Story.
The Capitalis is released during the FW campaign so player can prepare\* for the Fed campaign

*by now most players have a godfleet, therefore the Capitalis is a practical decoration
