### ISSUE TITLE
ARE Federation?

### ISSUE THREAD

**Issue by Amazinite** [Amazinite/Shields-Up#61]
@Disiuze has talked about still working with the Federation. In the files, they appear to have all their own outfits and some of their own ships. So what's up with them right now? Are they a splinter-faction of the Syndicate, per-previous Federation worlds? 

Are they T1, or did they do something to get an upper hand on the rest of humanity, save for maybe the Deep? Maybe they're the Syndicate's version of the Republic's Deep?

**Comment by Disiuze** [comment]
Spoilers (not that it matters)
Basically the Federation is the combination of the Union and Penum when I decided I couldn't work on them at the same time.
They're related to the Sentarians.

Yeah, they're kinda the Deep of the Syndicate.

**Comment by Amazinite** [comment]
So where are they going to be? If anything, I think the northern-most 4 or 5 syndicate systems makes the most sense, not where they were before.

**Comment by Disiuze** [comment]
For the time being I'm going to keep them where they are.
