### ISSUE TITLE
Predator and Hunter Drone

### ISSUE THREAD

**Issue by Amazinite** [Amazinite/Shields-Up#62]
The Predator (Shields Up) and Hunter Drone (ARE) are essentially the same thing; Sparrow drones often used in southern space meant to carry missiles. But the Finch exists now, which is a Sparrow fighter able to carry a set of missile launchers, so I think it would make sense to get rid of these two ships.

**Comment by Amazinite** [comment]
And while on the topic of drones, what's up with the Auto Scout (ARE)?

**Comment by Disiuze** [comment]
Hunter Drone is also used in the Deep, a simple rebranding will work. (The Hunter Drone was also a direct copy from the Predator except the Predator didn't work at the time)
The Auto Scout is for the Federation, it'll relate to their story.

**Comment by Amazinite** [comment]
I think it would make sense to get rid of the Predator and just use the Hunter Drone as a Deep/North specific drone, as the South, as said, has its Finch.

**Comment by Disiuze** [comment]
Sounds reasonable.

**Comment by Amazinite** [comment]
c0d5643
