### ISSUE TITLE
errors in servorum and plentipotent ship descriptions

### ISSUE THREAD

**Issue by Mark4666** [Amazinite/Shields-Up#63]
"The standard cargo ship for the Servorum Dei. Capable of carrying a medium load, while still being able to protect itself, the Servorum Dei use this ship in their fleets to extend their _**trad**_ across the galaxy."

**Comment by Mark4666** [comment]
albacore description gives ship type as interceptor but actual ship type is light warship

"The Albacore is the Servorum Dei's attempts at creating an **_interceptor_** capable of defending it's land from enemy ships of similar variety."

**Comment by Mark4666** [comment]
gramatical error in corvo description

"The Corvo is FTek's interpretation of a small freighter mixed with a transport. So in other words, it's **_basically interceptor._**"

**Comment by Mark4666** [comment]
Sica description gives ship type as interceptor but actual ship type is light warship.

"FTek's attempts to create an **_interceptor_** that is not only capable of handling it's energy usage and it's coolant levels, but also capable of dealing serious amounts of damage finally pays off in the Sica model."

**Comment by Mark4666** [comment]
kukri description gives ship type as light warship but actual ship type is medium warship

"The FTek Kukri **_light warship_** was originally designed to be used by the Servorum Dei, however after a slight mix-up (and a few threats) the design was eventually give to the Plenipotent Dominion. With a fair supply of fuel and firepower, this ship is ideal for making quick jumps into enemy territory to launch quick assaults, then escape before the enemy could really react."

**Comment by Amazinite** [comment]
Categories were changed on most of those ships. Worrying about stats now, descriptions later.

**Comment by Amazinite** [comment]
cf705df
