### ISSUE TITLE
Some random ideas to make Servorum outfits unique

### ISSUE THREAD

**Issue by Amazinite** [Amazinite/Shields-Up#64]
I'm wanting to give the Servorum their own T1.5 outfits. Here's some random ideas on what to do with them. 

- Have their steering outfits of a certain grade be bigger than the thrusters, unlike all other races where the thrusters are bigger than the steering. 
  - To compensate, all thrusters have integrated afterburners that instead of consuming fuel produce a massive amount of heat and require a lot of energy. 
- Instead of using AM turrets they use large jammers that fit onto a turret slot.
- Wanting the Particle Accelerator to be something the Servorum made before splitting off from the Dominion (#51). Suggest having other Servorum weapons be similar quick-burst weapons
- No shield generators, but most outfits have slight shield generation to them.
- Overall run cold but have high energy requirements.

**Comment by Disiuze** [comment]
Everything sounds good in my opinion, don't know what Friendly feels about it though.

**Comment by gunqqer** [comment]
I like the idea of integrated afterburners that don't use fuel

**Comment by Amazinite** [comment]
Thinking up some random names.

### Engines (Names after constellations)

**Tiny**: Aries
**Small**: Draco
**Medium**: Hydra
**Large**: Orion
**Huge**: Sagittarius

### Energy Storage (Names after gemstones)

**Tiny**: Zircon Power Storage
**Small**: Sapphire Power Storage
**Medium**: Ruby Power Storage
**Large**: Emerald Power Storage
**Huge**: Diamond Power Storage

### Energy Generation (Random names)

**Tiny**: Piezoelectric Generator (name sounds cool, but the actual method of electricity making is [probably completely shit IRL](https://en.wikipedia.org/wiki/Energy_harvesting#Piezoelectric). Also not alphabetical, soooo....)
**Medium**: Cold Fusion Reactor
**Large**: Gravitational Induction Core
**Huge**: Plasmatic Fusion Ring

### Cooling

**Small**: Dynamic Heat Pump (the dynamic part is to make it sound cool)
**Large**: Absolute Zero Cooling

**Comment by Amazinite** [comment]
```
outfit "Overdrive Aries Thruster"
    category "Engines"
    "cost" 95000
    thumbnail "outfit/unknown"
    "mass" 9
    "outfit space" -9
    "engine capacity" -9
    "thrust" 6.8
    "afterburner thrust" 6.8
    "thrusting energy" 3.4
    "afterburner energy" 6.8
    "thrusting heat" .9
    "afterburner heat" 1.8
    "flare sprite" "effect/plasma flare/tiny"
        "frame rate" 5
    "flare sound" "plasma tiny"
    "afterburner effect" "afterburner"
```

>   description "Servorum Overdrive Thrusters have the interesting characteristic of possessing integrated afterburners. Activating these afterburners doubles the effective thrust but triples the amount of energy used and heat produced."

```
outfit "Overdrive Aries Steering"
    category "Engines"
    "cost" 195000
    thumbnail "outfit/unknown"
    "mass" 18
    "outfit space" -18
    "engine capacity" -18
    "turn" 484
    "turning energy" 3.1
    "turning heat" 0.8
    "energy capacity" 580
```

>   description "Unlike the engines of other species, the Servorum have developed their steering outfits to be larger than their thruster outfits of the same size. This is to allow more space to integrate batteries into the steering that support the Overdrive Afterburners on the thrusters."

**Comment by Amazinite** [comment]
```
outfit "Zircon Power Storage"
    category "Power"
    cost 40000
    thumbnail "outfit/unknown"
    "mass" 20
    "outfit space" -20
    "energy capacity" 1800
    "shield generation" 0.4
    "shield energy" 0.6
```

>   description "Servorum power storage systems double as shield generators for their ships. Although the energy capacity efficiency decreases as the size increases, the shield generation greatly increases."

**Comment by Amazinite** [comment]
27e6de7
Enjoy.

**Comment by Amazinite** [comment]
Just need to give them some more weapons.
