### ISSUE TITLE
unknown system

### ISSUE THREAD

**Issue by Phil-Morley** [Amazinite/Shields-Up#67]
Right next and partly overlapping Kor Men (NE of sheratan) is a system that has no name. It doesn't have a planet symbol but you can click on it and go there. Sorry haven't been able to find it in files. My savefile just says travel ""

**Comment by Amazinite** [comment]
Yeah, I have it too, and I've known about it for a long time now. I don't know where it comes from exactly.

**Comment by Phil-Morley** [comment]
ok :)

**Comment by murrayvb0** [comment]
I think this has something to do with Alphean's. Pretty sure theres a syntax error somewhere but i can't seem to find it. If it helps at all for whatever reason Alphean's has the only map file that I can't open in MZ's map editor.

**Comment by Amazinite** [comment]
If there was a syntax error then it would show up in errors.txt, but I'm not getting anything.

**Comment by murrayvb0** [comment]
Well there's at least something going on in Alpheans' map.txt

**Comment by murrayvb0** [comment]
Just looked through all the map files again. It's definitely something in Alphean's... The question is what.

**Comment by Amazinite** [comment]
Well if you can tell by looking at the file, then can you point me to where...?

**Comment by murrayvb0** [comment]
I don't know what exactly is happening but for whatever reason all the map files besides alphean's load properly in MZ's map editor. Alphean's map file appears to have a 50-50 chance of just not loading or crashing the tool entirely. What i meant when I said looked through the files I meant that I tested everything and made sure there was no weird errors in the files, the only thing that I really saw was some indentation stuff along with alphean's weird interaction with the map editor.

**Comment by murrayvb0** [comment]
Alright ignore what I just said. Turns out one of my map editor dlls didn't unzip properly. Alphean's map file is now loading properly.

**Comment by murrayvb0** [comment]
Ok I'm back with some actually constructive input this time. I disabled all plugins on my installation and it's still here. It appears to be a problem with the base game. I'll go see if there are any issues related to this in the github repository.

**Comment by Amazinite** [comment]
It's been found out that this is an issue with the vanilla game, and should be fixed in v0.9.5 of Endless Sky.
