### ISSUE TITLE
Mark II stealth cruiser broken

### ISSUE THREAD

**Issue by Mark4666** [Amazinite/Shields-Up#68]
event causing mark II stealth spawn has no trigger date and spawns with no hull, cargo space, bunks, fuel capacity, hull mass, outfit space, weapon or engine capacity.

fleet spawn event, mark II variant info and image of newly captured stealth cruiser below.

event "stealth cruiser service mark ii"
	fleet "Large Republic"
		government "Republic"
		names "republic capital"
		fighters "republic fighter"
		cargo 0
		personality
			heroic
		variant 4
			"Frigate (Mark II)" 2
			"Rainmaker (Mark II)"
			"Gunboat (Mark II)"
		variant 1
			"Frigate" 2
			"Rainmaker"
			"Gunboat"
		variant 2
			"Cruiser (Mark II)"
			"Combat Drone" 4
		variant 1
			"Cruiser"
			"Combat Drone" 4
		variant 2
			"Cruiser (Mark II)"
			"Combat Drone" 4
			"Frigate (Mark II)"
			"Rainmaker (Mark II)"
		variant 1
			"Cruiser"
			"Combat Drone" 4
			"Frigate"
			"Rainmaker"
		variant 2
			"Carrier (Mark II)"
			"Lance" 4
			"Combat Drone" 6
		variant 1
			"Carrier"
			"Lance" 4
			"Combat Drone" 6
		variant 1
			"Carrier (Mark II)"
			"Lance" 4
			"Combat Drone" 6
			"Cruiser (Mark II)"
			"Combat Drone" 4
			"Frigate (Mark II)" 2
			"Rainmaker (Mark II)" 2
			"Gunboat (Mark II)" 2
		variant 1
			"Cruiser (Mark II)"
			"Combat Drone" 4
			"Frigate (Mark II)" 2
		variant 1
			"Frigate (Mark II)"
			"Rainmaker (Mark II)" 2
			"Gunboat (Mark II)"
		variant 1
			"Stealth Cruiser (Navy MkII)" 2

ship "Stealth Cruiser" "Stealth Cruiser (Navy MkII)"
	attributes
		"shields" 8500
	outfits
		Hyperdrive
		"X3700 Ion Thruster"
		"X4200 Ion Steering"
		"Electron Beam" 4
		"Heavy Anti-Missile Turret" 2
		"Fusion Reactor"
		"LP072a Battery Pack"
		"Liquid Helium Cooler"
		"D67-TM Shield Generator"
		"Navy Cloaking Device"
	gun "Electron Beam"
	gun "Electron Beam"
	gun "Electron Beam"
	gun "Electron Beam"
	turret "Heavy Anti-Missile Turret"
	turret "Heavy Anti-Missile Turret"

![stealth cruiser](https://cloud.githubusercontent.com/assets/22483942/20861412/77f163a0-b987-11e6-98c9-8cc52ac1bcdf.png)

**Comment by Amazinite** [comment]
d32e9ba Removed for now.
My plan was to remove it and readd it after creating some sort of quest that explains why the Navy is able to produced cloaking devices.
