### ISSUE TITLE
error in deceptive lover desc.

### ISSUE THREAD

**Issue by Mark4666** [Amazinite/Shields-Up#69]
description lists ship as having two turrets but there are no turrets in the hardpoint listings (bold) and there is also a grammatical error (italics)

"Aye! She looks pretty, but she's got a heart of stone and will put a knife your ribs when your not looking! One of our newer designs, it's got six long guns and **two turrets** _as well the shielding_ to take a hit!"

gun -34 -24 "Plasma Cannon"
	gun -27 -49 "Plasma Cannon"
	gun -17.5 -73 "Plasma Cannon"
	gun 17 -73 "Plasma Cannon"
	gun 26.5 -46 "Plasma Cannon"
	gun 34 -21 "Plasma Cannon"
	explode "small explosion" 30
	explode "tiny explosion" 20
	explode "medium explosion" 20
	explode "big explosion" 5
	"final explode" "final explosion big" 1

**Comment by Amazinite** [comment]
Removed the line about turrets instead of giving it ones. Comparing it to The Screams of the Insane, which has 2 turrets and 4 guns, I would think that The Deceptive Lover was only suppose to have the 6 guns.
bacbc1f
