### ISSUE TITLE
error in phoenix outfit listings/gun hardpoints

### ISSUE THREAD

**Issue by Mark4666** [Amazinite/Shields-Up#70]
outfit listings have the forward guns as 2  **400mm Mag Rail Cannons** and 2 Torpedo Launchers but the gun hardpoints lists them as 2 _400mm Railguns_ and 2 Torpedo launchers

outfits
	**"400mm Mag Rail Cannon"** 2
	"400mm Slug" 100
	"Torpedo Launcher" 2
	"Torpedo" 60
	"Heavy Laser Turret" 3
	"Heavy Anti-Missile Turret" 2

"Fusion Reactor"
"LP072a Battery Pack"
"D94-YV Shield Generator"
"Liquid Nitrogen Cooler"

"X3700 Ion Thruster"
"X4200 Ion Steering"
"Scram Drive"

engine -31 81
engine 32.5 81
gun -55 -38 _"400mm Railgun"_
gun 55 -38 _"400mm Railgun"_
gun -26 -13 "Torpedo Launcher"
gun 26 -13 "Torpedo Launcher"
turret -54 -4 "Heavy Laser Turret"
turret 54 -4 "Heavy Laser Turret"
turret 0 -9 "Heavy Laser Turret"
turret -30 27 "Heavy Anti-Missile Turret"
turret 30 27 "Heavy Anti-Missile Turret"

**Comment by Amazinite** [comment]
bacbc1f
