### ISSUE TITLE
Too many variants in Phil's Flavours

### ISSUE THREAD

**Issue by Amazinite** [Amazinite/Shields-Up#73]
There are so many variants that the entire fleet file is 12k lines long. That's as long as a large map file. I think that the number of variants per ship should be cut down to 1 or 2 instead of 3+ like I've seen on some and there shouldn't be any new variants for vanilla ships.

**Comment by Phil-Morley** [comment]
ok will cut them down

**Comment by Phil-Morley** [comment]
Still happy to cut but thinking more on this. In general I roughly worked on 3 variants with combinations of long or short lasers, particle cannon turrets, plasma/proton and at least 1 of those variants would have atomic engines and 1 would have missiles in the gun ports. This was mostly to get more variability in the weapons and to see ships flying around using the weapons I had made. I feel a bit the same way with SU weapons. There is a heap of great and interesting weapons that have been made but the ships flying around don't use them, I could see the navy using ion turrets to make you stop, pirates with emp bombs etc. What if stick with 3 of each using all the SU weapons, but some of the variants are not common so the fleets files are smaller?

**Comment by Amazinite** [comment]
I've been working on stuff for the vanilla game lately so I haven't really been able to work on the fleets, but remaking all the fleets and making variants that actually use some of the SU outfits is on my todo list.

**Comment by Amazinite** [comment]
a1ed2e7
