### ISSUE TITLE
paul mission chain

### ISSUE THREAD

**Issue by Phil-Morley** [Amazinite/Shields-Up#74]
the paul mission chain requires a light freighter to continue from splashdown. There is no mention of this and if you do not have a light freighter the mission chain ends without knowing why. Needs to either mention that light freighter is needed or remove has light freighter from mission "Ext Intro [Cargo 1]" in Paul mission chain.txt

**Comment by FriendlyNeighbour** [comment]
One sec, checking it out

**Comment by FriendlyNeighbour** [comment]
I think you may be a bit confused on how that chain is set up. Cargo 1 requires a light freighter, and there are two other chains depending on 2hat type of ship you have. Although looking back at it, we could probably have an "or" command in some, since when the player finds the chain, they may have a heavy freighter.

**Comment by Phil-Morley** [comment]
ok, I took him to splashdown and it said go to the spaceport to continue. Went to spaceport and nothing happens, was left wondering where he was. Left and come back trying to find him etc. Ended up looking at the mission chain to try and work out where he went :) removed the requirement for light freighter and we are going again :)

**Comment by FriendlyNeighbour** [comment]
What ship class were you in

**Comment by Phil-Morley** [comment]
heavy warship

**Comment by FriendlyNeighbour** [comment]
Ok, so the problrm isn't that it requires a loght freighter, it's that the interceptor mission needs to have something like: requires interceptor *or* heavy warship

Same with medium warships, etc.
The Paul mission chain had 3 different trees, one for if you picked a cargo ship, another for transport, another for interceptor. We just need to add the other ships classes in for their respective chains. Combat based classes need to be added as requirements for the interceptor 1 chain. Get what I'm saying?

In the code, scroll down past the cargo chain and you'll see the other chains

**Comment by Phil-Morley** [comment]
yep, cool

**Comment by FriendlyNeighbour** [comment]
Are we sure the way it's written now works? We have multiple ship types listed. Do we not need an "or" line?

Like: requires interceptor *or* heavy warship?
And we also need to add the other ship classes to the cargo chain, since right now we only have light freighters set up for it

**Comment by Amazinite** [comment]
Going to fix it.

**Comment by FriendlyNeighbour** [comment]
Thank you, I'd love to help as well but I'm currently not at home :/

**Comment by Amazinite** [comment]
fce22eb
Phil had it right, he just missed the heavy freighter part.

**Comment by Amazinite** [comment]
Keeping open till we update.

**Comment by FriendlyNeighbour** [comment]
Okay, sweet. Just because I'm curious, do you know why that doesn't require
someone seperating the requirements?  Because the way it's written now
seems like it would require you to have all of thosetypes of ships.

**Comment by Amazinite** [comment]
MZ is weird, It's just how the syntax is. While it looks like you would need all of those, it actually reads like "interceptor or light warship or medium warship or heavy warship."

**Comment by FriendlyNeighbour** [comment]
Ah. Thanks.
