### ISSUE TITLE
Some silver ships don't have markings

### ISSUE THREAD

**Issue by Amazinite** [Amazinite/Shields-Up#75]
Given that some of the silver ships don't have markings on them, you can't tell what government they are from without clicking on them. Suggested either giving them some sort of colored marking to be swizzled or only make them part of one faction.

**Comment by Phil-Morley** [comment]
yes, I created them and thought they don't really fit stylistically as normal human ships, but they are also not quite alien. I was trying to think of a new race or faction that used them or a post FW storylines to introduce them as a new shipyard but was stuck in feature creep and never getting the mod out, so dumped them in Vega. I think I will pull them out and try again at coming up with some story or somewhere for them to be from.

**Comment by Phil-Morley** [comment]
Also where are the rest of shields up ships being incorporated? seems that my fleets are the last loaded? but I saw ironclad / pirated frigate etc come up, I feel need to adjust frequencies of ship appearing (increase for the vanilla ships and definitely more of the other SU ships so that mine are not dominating so much)

**Comment by Amazinite** [comment]
The fleet compat folder has all the fleets in it so that no ones gets overrided, but I'm not entirely sure if it's needed because I'm seeing a few ships from other mods that aren't in the fleet compat folder, meaning they aren't being overridden.

**Comment by Phil-Morley** [comment]
thanks

**Comment by Amazinite** [comment]
That black star ship doesn't have markings either, although I'm not sure if it's already pirate only.

**Comment by Amazinite** [comment]
8978045 Silver ships are now unqiue to the merchant government, excluding the two Star ships which are pirate only ships.
