### ISSUE TITLE
Turn nebula images into system haze

### ISSUE THREAD

**Issue by Amazinite** [Amazinite/Shields-Up#77]
The next update is going to allow us to be able to set the haze that appears in a system, so we can change it from the normal blue haze that occurs right now. Might be worth testing out turning the nebula images into haze and see how that turns out.

**Comment by FriendlyNeighbour** [comment]
Sounds like a good idea

**Comment by Amazinite** [comment]
Going to try this now.

**Comment by Amazinite** [comment]
This looks awesome.
![](http://image.prntscr.com/image/1f45fa8c63f94939b065e2fefeb47134.png)

**Comment by Amazinite** [comment]
We could animate it too. :3

**Comment by Amazinite** [comment]
542fca1
