### ISSUE TITLE
Add special plural cases to ships and outfits

### ISSUE THREAD

**Issue by Amazinite** [Amazinite/Shields-Up#79]
There's a new thing where you can set the plural form of a ship or outfit's name so that it gets used properly in the case that the plural of an outfit is called. Normally it just adds and S to the end of the word to set it plural, but this isn't the case for all words, so anything that would need to end -es or -ies needs a special plural form specified.

**Comment by Phil-Morley** [comment]
Worked through and *think* I've got them all.

**Comment by Amazinite** [comment]
I'll check through later and close this if you got it all.

**Comment by Amazinite** [comment]
cf0ca23
