### ISSUE TITLE
Work on making human jobs offer in Deep Sky space

### ISSUE THREAD

**Issue by Amazinite** [Amazinite/Shields-Up#83]
Removed them all for compatibility reasons. Rework how it was done so it works better. Maybe just make the planets be Republic government but the systems Deep Sky?

**Comment by Amazinite** [comment]
I'll test if e5c53d8 made this work later.

**Comment by Amazinite** [comment]
Doesn't work as is. Also, what's the purpose of the Zorica system with that Rodin planet?

**Comment by FriendlyNeighbour** [comment]
It had a purpose a long time ago, but due to changes in the Dominion and
Servorum Dei's stories and system locations, it really has no relevant
function except for having a cool name that doesn't match the naming scheme
of the Deep.

**Comment by Amazinite** [comment]
802a6db Just removing the government, since it isn't needed. I might try and PR a seperate Deep government into the game, seeing as how they describe themselves as being somewhat autonomous like the Syndicate or the FW after the war. Then, if we need a Deep Sky government, it will be in the game.
