### ISSUE TITLE
Standardize Mil'taj vs Militaj

### ISSUE THREAD

**Issue by Amazinite** [Amazinite/Shields-Up#85]
It changes in some places.

**Comment by FriendlyNeighbour** [comment]
Mil'taj should be the standardized form. Places i know it is militaj is
outfit names and the government file. Although because the government is
Militaj it may be much simpler to go with Militaj

**Comment by Disiuze** [comment]
Go big or go home; M'l'taj or Militaj, and I think "Militaj" is better.

**Comment by Amazinite** [comment]
Where the hell did you people come from?

**Comment by FriendlyNeighbour** [comment]
I'm on my phone
-Friendly Neighbour

**Comment by Amazinite** [comment]
Standarized to "Mil'taj" in 18485ba, along with some other changes.
