### ISSUE TITLE
Shrink Mil'taj space?

### ISSUE THREAD

**Issue by Amazinite** [Amazinite/Shields-Up#88]
Even after moving the systems around to make Mil'taj space more compact, they still take up quite a bit of the universe, and it just feels like a waste when most of it is uninhabited. I'm thinking of shrinking it down to maybe 2/3rds or even a half of its current size, and reducing the number of inhabited systems to match how supposedly crushed they were by the Drak/Quarg (maybe like 5 inhabited systems tops instead of the current 11).

**Comment by FriendlyNeighbour** [comment]
Sounds like a wise decision.

**Comment by Amazinite** [comment]
Done in 6b30f9f
