### ISSUE TITLE
Add Enigma Corp into SU?

### ISSUE THREAD

**Issue by Amazinite** [Amazinite/Shields-Up#9]
Maybe. I don't know. My only reason behind asking this is because there are a lot of outfits in SU that are also in EC, namely the secondary weapon ammunition increasers and shield buffers. There's also the weapon and engine space increasers, the only difference being that mine uses cargo instead of outfit space as well as having no weird side effects like heat generation. And heck, there is already that one mission in Alphean that requires a Navy license to start, which one would get from my mod seeing as how the license mission was removed in AE.

**Comment by Disiuze** [comment]
"Weird side effects" are because you are modifying your ship, and to not become unstable in one place, it needs something that keeps it together, like something that creates heat or uses energy,

**Comment by Amazinite** [comment]
How does that line up with the vanilla cargo and mass expansions, which have no side effects to them?

**Comment by Amazinite** [comment]
Probably won't do this, at least not for now.

**Comment by FriendlyNeighbour** [comment]
As for adding Enigma Corp into SU, that doesn't sound like a terrible idea. I would have to check with how Direstorm feels about that. I agree with Disi on the side effects of the enhancements. A difference between those enhancements and the vanilla enhancements I think would be that Engine and Weapons extensions are a bit more technical, with things like a lot more wiring needed to connect all this space together, whereas in vanilla, making a cargo bay into a couple rooms isn't as technical. (not sure if any of that made any sense what-so-ever)

**Comment by Amazinite** [comment]
Makes sense, but then I would think that both would require energy and not have one require energy while the other produces heat.

**Comment by FriendlyNeighbour** [comment]
I agree with that. Perhaps engine extensions produces heat, weapons requires energy?

**Comment by Amazinite** [comment]
I'll bring Enigma Corp into SU after v0.5.5, then I can work on Blender and try and do sprites for everyone's missing outfits.

**Comment by Amazinite** [comment]
I've decided against brining Enigma Corp isn't SU, at least for now. The only reason I would really want to merge the two is to avoid conflicts if we both change something in vanilla, and my mod doesn't have any big vanilla changes that would conflict with Shields Up as of yet. I do plan on making changes to merchant fleets in the future, in which case that would conflict with SU merchant fleets, but until then I'd like to keep them separate.
