### ISSUE TITLE
Tyil

### ISSUE THREAD

**Issue by Amazinite** [Amazinite/Shields-Up#91]
Is there really any purpose for them other than being another outfit and ship developer?
I'm thinking of removing them and their systems and giving the outfits and ships to someone else.

**Comment by Disiuze** [comment]
> Is there really any purpose for them other than being another outfit and ship developer?  

That's all they are, the only reason they really exist is because of the grenade launcher and the Goose.

**Comment by Amazinite** [comment]
k

**Comment by Amazinite** [comment]
d815806 removed them from the main mod
