### ISSUE TITLE
Story Idea: The Federation

### ISSUE THREAD

**Issue by Amazinite** [Amazinite/Shields-Up#95]
Right now there are outfits and ships for a human faction known as the Federation that aren't actually in use. The original idea is that they would be "the Deep of the Syndicate, influence by the Sentar instead of the Pug." Thinking about it a bit, this wouldn't really work out too well with the current politics of the game, having a random faction just spring up independent of the Syndicate. But what would work is a worker's revolt against the Syndicate.

So the idea goes as follows: Syndicate space is clearly a region of pretty massive income inequality. Workers are signed onto contracts for 5+ years and pretty much forced to work their way out, only to either have to continue working after their contract ends of have to move to a crappy frontier world that could kill them. On the ES wiki, MZ has a story idea that involves a poor vs rich situation, and this could be just that (meaning that I would actually consider PRing this into the game). 

The story starts when a large worker strike happens on some of the largest Syndicate worlds. Now that might not be too uncommon, but this would be the biggest one in history. The entire human economy gets impacted because of it (something we sadly can't easily portray in game). This eventually leads to a number of frontier worlds, full of people who were once workers and know the struggle of those currently striking, threaten secession. Just so it isn't a repeat of the FW campaign, secession never actually happens, but the (Workers?) Federation "government" does form, flying their own colors. The Republic, which the Syndicate has a lot of sway in, sides with the Syndicate, but the Free Worlds are more inclined to side with the Federation. 

This wouldn't be as long a campaign as something like the FW (it would be more of a mini-campaign of say 50 missions max), and all-out-war wouldn't occur (probably nothing more than one or two spark battles that occur between Federation and Syndicate ships), but it would probably be an interesting story that could help to flesh out the game universe. 

(Given the situation though, the current outfits and ships listed for the Federation either need repurposed or dumped).

**Comment by FriendlyNeighbour** [comment]
Thst sounds pretty cool!

**Comment by Amazinite** [comment]
The part on the wiki that talks about a rich vs. poor story also mentions servants in the Paradise Worlds, so they might be able to be tied in somehow.

**Comment by FriendlyNeighbour** [comment]
Perhaps somewhere along the Syndicate workers forming the federation, the
paradise world slaves get a similar idea and ask for Federation assistance.
Although seems like the Republic presence in the paradise worlds would shut
that down pretty quick.

**Comment by Amazinite** [comment]
d815806 deprecated the current Federation outfits and ships

**Comment by Amazinite** [comment]
Putting this in my story idea folder for later. The issue doesn't need to exist.
